(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var g;function aa(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}function p(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):{next:aa(a)}}var ba="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},ca;
if("function"==typeof Object.setPrototypeOf)ca=Object.setPrototypeOf;else{var da;a:{var ea={P:!0},fa={};try{fa.__proto__=ea;da=fa.P;break a}catch(a){}da=!1}ca=da?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var ha=ca;
function ia(a,b){a.prototype=ba(b.prototype);a.prototype.constructor=a;if(ha)ha(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.H=b.prototype}var ja="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};
function ka(a){a=["object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global,a];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var q=ka(this);function r(a,b){if(b){var c=q;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&ja(c,a,{configurable:!0,writable:!0,value:b})}}function la(){la=function(){};q.Symbol||(q.Symbol=ma)}
function na(a,b){this.a=a;ja(this,"description",{configurable:!0,writable:!0,value:b})}na.prototype.toString=function(){return this.a};var ma=function(){function a(c){if(this instanceof a)throw new TypeError("Symbol is not a constructor");return new na("jscomp_symbol_"+(c||"")+"_"+b++,c)}var b=0;return a}();
function oa(){la();var a=q.Symbol.iterator;a||(a=q.Symbol.iterator=q.Symbol("Symbol.iterator"));"function"!=typeof Array.prototype[a]&&ja(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return pa(aa(this))}});oa=function(){}}function pa(a){oa();a={next:a};a[q.Symbol.iterator]=function(){return this};return a}
var qa=function(){function a(){function c(){}new c;Reflect.construct(c,[],function(){});return new c instanceof c}if("undefined"!=typeof Reflect&&Reflect.construct){if(a())return Reflect.construct;var b=Reflect.construct;return function(c,d,e){c=b(c,d);e&&Reflect.setPrototypeOf(c,e.prototype);return c}}return function(c,d,e){void 0===e&&(e=c);e=ba(e.prototype||Object.prototype);return Function.prototype.apply.call(c,e,d)||e}}();r("Reflect.construct",function(){return qa});
r("Object.setPrototypeOf",function(a){return a||ha});r("Array.from",function(a){return a?a:function(b,c,d){c=null!=c?c:function(k){return k};var e=[],f="undefined"!=typeof Symbol&&Symbol.iterator&&b[Symbol.iterator];if("function"==typeof f){b=f.call(b);for(var h=0;!(f=b.next()).done;)e.push(c.call(d,f.value,h++))}else for(f=b.length,h=0;h<f;h++)e.push(c.call(d,b[h],h));return e}});function t(a,b){return Object.prototype.hasOwnProperty.call(a,b)}
r("WeakMap",function(a){function b(l){this.a=(k+=Math.random()+1).toString();if(l){l=p(l);for(var m;!(m=l.next()).done;)m=m.value,this.set(m[0],m[1])}}function c(){}function d(l){var m=typeof l;return"object"===m&&null!==l||"function"===m}function e(l){if(!t(l,h)){var m=new c;ja(l,h,{value:m})}}function f(l){var m=Object[l];m&&(Object[l]=function(n){if(n instanceof c)return n;e(n);return m(n)})}if(function(){if(!a||!Object.seal)return!1;try{var l=Object.seal({}),m=Object.seal({}),n=new a([[l,2],[m,
3]]);if(2!=n.get(l)||3!=n.get(m))return!1;n.delete(l);n.set(m,4);return!n.has(l)&&4==n.get(m)}catch(N){return!1}}())return a;var h="$jscomp_hidden_"+Math.random();f("freeze");f("preventExtensions");f("seal");var k=0;b.prototype.set=function(l,m){if(!d(l))throw Error("Invalid WeakMap key");e(l);if(!t(l,h))throw Error("WeakMap key fail: "+l);l[h][this.a]=m;return this};b.prototype.get=function(l){return d(l)&&t(l,h)?l[h][this.a]:void 0};b.prototype.has=function(l){return d(l)&&t(l,h)&&t(l[h],this.a)};
b.prototype.delete=function(l){return d(l)&&t(l,h)&&t(l[h],this.a)?delete l[h][this.a]:!1};return b});
r("Map",function(a){function b(){var k={};return k.o=k.next=k.head=k}function c(k,l){var m=k.a;return pa(function(){if(m){for(;m.head!=k.a;)m=m.o;for(;m.next!=m.head;)return m=m.next,{done:!1,value:l(m)};m=null}return{done:!0,value:void 0}})}function d(k,l){var m=l&&typeof l;"object"==m||"function"==m?f.has(l)?m=f.get(l):(m=""+ ++h,f.set(l,m)):m="p_"+l;var n=k.b[m];if(n&&t(k.b,m))for(k=0;k<n.length;k++){var N=n[k];if(l!==l&&N.key!==N.key||l===N.key)return{id:m,list:n,index:k,g:N}}return{id:m,list:n,
index:-1,g:void 0}}function e(k){this.b={};this.a=b();this.size=0;if(k){k=p(k);for(var l;!(l=k.next()).done;)l=l.value,this.set(l[0],l[1])}}if(function(){if(!a||"function"!=typeof a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var k=Object.seal({x:4}),l=new a(p([[k,"s"]]));if("s"!=l.get(k)||1!=l.size||l.get({x:4})||l.set({x:4},"t")!=l||2!=l.size)return!1;var m=l.entries(),n=m.next();if(n.done||n.value[0]!=k||"s"!=n.value[1])return!1;n=m.next();return n.done||4!=n.value[0].x||
"t"!=n.value[1]||!m.next().done?!1:!0}catch(N){return!1}}())return a;oa();var f=new WeakMap;e.prototype.set=function(k,l){k=0===k?0:k;var m=d(this,k);m.list||(m.list=this.b[m.id]=[]);m.g?m.g.value=l:(m.g={next:this.a,o:this.a.o,head:this.a,key:k,value:l},m.list.push(m.g),this.a.o.next=m.g,this.a.o=m.g,this.size++);return this};e.prototype.delete=function(k){k=d(this,k);return k.g&&k.list?(k.list.splice(k.index,1),k.list.length||delete this.b[k.id],k.g.o.next=k.g.next,k.g.next.o=k.g.o,k.g.head=null,
this.size--,!0):!1};e.prototype.clear=function(){this.b={};this.a=this.a.o=b();this.size=0};e.prototype.has=function(k){return!!d(this,k).g};e.prototype.get=function(k){return(k=d(this,k).g)&&k.value};e.prototype.entries=function(){return c(this,function(k){return[k.key,k.value]})};e.prototype.keys=function(){return c(this,function(k){return k.key})};e.prototype.values=function(){return c(this,function(k){return k.value})};e.prototype.forEach=function(k,l){for(var m=this.entries(),n;!(n=m.next()).done;)n=
n.value,k.call(l,n[1],n[0],this)};e.prototype[Symbol.iterator]=e.prototype.entries;var h=0;return e});var u=this||self;function ra(a){if(a&&a!=u)return sa(a.document);null===ta&&(ta=sa(u.document));return ta}var ua=/^[\w+/_-]+[=]{0,2}$/,ta=null;function sa(a){return(a=a.querySelector&&a.querySelector("script[nonce]"))&&(a=a.nonce||a.getAttribute("nonce"))&&ua.test(a)?a:""}function va(a,b){a=a.split(".");b=b||u;for(var c=0;c<a.length;c++)if(b=b[a[c]],null==b)return null;return b}function wa(){}
function v(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b}function xa(a){var b=v(a);return"array"==b||"object"==b&&"number"==typeof a.length}function w(a){var b=typeof a;return"object"==b&&null!=a||"function"==b}function ya(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var d=c.slice();d.push.apply(d,arguments);return a.apply(this,d)}}var za=Date.now||function(){return+new Date};
function Aa(a,b){function c(){}c.prototype=b.prototype;a.H=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.Z=function(d,e,f){for(var h=Array(arguments.length-2),k=2;k<arguments.length;k++)h[k-2]=arguments[k];return b.prototype[e].apply(d,h)}};var Ba=String.prototype.trim?function(a){return a.trim()}:function(a){return/^[\s\xa0]*([\s\S]*?)[\s\xa0]*$/.exec(a)[1]};
function Ca(a,b){if(b)a=a.replace(Da,"&amp;").replace(Ea,"&lt;").replace(Fa,"&gt;").replace(Ga,"&quot;").replace(Ha,"&#39;").replace(Ia,"&#0;");else{if(!Ja.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(Da,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(Ea,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(Fa,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(Ga,"&quot;"));-1!=a.indexOf("'")&&(a=a.replace(Ha,"&#39;"));-1!=a.indexOf("\x00")&&(a=a.replace(Ia,"&#0;"))}return a}
var Da=/&/g,Ea=/</g,Fa=/>/g,Ga=/"/g,Ha=/'/g,Ia=/\x00/g,Ja=/[\x00&<>"']/;function x(a,b){return-1!=a.indexOf(b)}function Ka(a,b){return a<b?-1:a>b?1:0};var y;a:{var La=u.navigator;if(La){var Ma=La.userAgent;if(Ma){y=Ma;break a}}y=""};var Na;var z=Array.prototype.indexOf?function(a,b){return Array.prototype.indexOf.call(a,b,void 0)}:function(a,b){if("string"===typeof a)return"string"!==typeof b||1!=b.length?-1:a.indexOf(b,0);for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},Oa=Array.prototype.forEach?function(a,b,c){Array.prototype.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e="string"===typeof a?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)},Pa=Array.prototype.filter?function(a,b){return Array.prototype.filter.call(a,
b,void 0)}:function(a,b){for(var c=a.length,d=[],e=0,f="string"===typeof a?a.split(""):a,h=0;h<c;h++)if(h in f){var k=f[h];b.call(void 0,k,h,a)&&(d[e++]=k)}return d};function Qa(a){return Array.prototype.concat.apply([],arguments)}function Ra(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]};function Sa(a,b,c){for(var d in a)b.call(c,a[d],d,a)}function Ta(a,b){for(var c in a)if(b.call(void 0,a[c],c,a))return!0;return!1}var Ua="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");function Va(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<Ua.length;f++)c=Ua[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};function A(a,b){this.a=a===Wa&&b||"";this.b=Xa}g=A.prototype;g.G=!0;g.D=function(){return this.a.toString()};g.M=!0;g.v=function(){return 1};g.$=function(a,b){var c=Ya(this).toString();c=Za.exec(c);var d=c[3]||"";return new A(Wa,c[1]+$a("?",c[2]||"",a)+$a("#",d,b))};function Ya(a){if(a instanceof A&&a.constructor===A&&a.b===Xa)return a.a;v(a);return"type_error:TrustedResourceUrl"}var Za=/^([^?#]*)(\?[^#]*)?(#[\s\S]*)?/,Xa={};
function $a(a,b,c){if(null==c)return b;if("string"===typeof c)return c?a+encodeURIComponent(c):"";for(var d in c){var e=c[d];e=Array.isArray(e)?e:[e];for(var f=0;f<e.length;f++){var h=e[f];null!=h&&(b||(b=a),b+=(b.length>a.length?"&":"")+encodeURIComponent(d)+"="+encodeURIComponent(String(h)))}}return b}var Wa={};function B(a,b){this.a=a===ab&&b||"";this.b=bb}B.prototype.G=!0;B.prototype.D=function(){return this.a.toString()};B.prototype.M=!0;B.prototype.v=function(){return 1};function cb(a){if(a instanceof B&&a.constructor===B&&a.b===bb)return a.a;v(a);return"type_error:SafeUrl"}var bb={},ab={};function C(){this.a="";this.c=db;this.b=null}C.prototype.M=!0;C.prototype.v=function(){return this.b};C.prototype.G=!0;C.prototype.D=function(){return this.a.toString()};function eb(a){if(a instanceof C&&a.constructor===C&&a.c===db)return a.a;v(a);return"type_error:SafeHtml"}function fb(a){if(a instanceof C)return a;var b="object"==typeof a,c=null;b&&a.M&&(c=a.v());return gb(Ca(b&&a.G?a.D():String(a)),c)}
function hb(a){function b(f){Array.isArray(f)?Oa(f,b):(f=fb(f),e.push(eb(f).toString()),f=f.v(),0==d?d=f:0!=f&&d!=f&&(d=null))}var c=fb(ib),d=c.v(),e=[];Oa(a,b);return gb(e.join(eb(c).toString()),d)}function jb(a){return hb(Array.prototype.slice.call(arguments))}var db={};function gb(a,b){return kb(a,b)}function kb(a,b){var c=new C;c.a=a;c.b=b;return c}kb("<!DOCTYPE html>",0);var ib=kb("",0),lb=kb("<br>",0);var mb=function(a){var b=!1,c;return function(){b||(c=a(),b=!0);return c}}(function(){var a=document.createElement("div"),b=document.createElement("div");b.appendChild(document.createElement("div"));a.appendChild(b);b=a.firstChild.firstChild;a.innerHTML=eb(ib);return!b.parentElement});function nb(a,b){if(mb())for(;a.lastChild;)a.removeChild(a.lastChild);a.innerHTML=eb(b)};function ob(a){return a=Ca(a,void 0)};var pb="StopIteration"in u?u.StopIteration:{message:"StopIteration",stack:""};function qb(){}qb.prototype.next=function(){throw pb;};qb.prototype.a=function(){return this};function rb(a,b){this.b={};this.a=[];this.f=this.c=0;var c=arguments.length;if(1<c){if(c%2)throw Error("Uneven number of arguments");for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else if(a)if(a instanceof rb)for(c=a.s(),d=0;d<c.length;d++)this.set(c[d],a.get(c[d]));else for(d in a)this.set(d,a[d])}g=rb.prototype;g.h=function(){D(this);for(var a=[],b=0;b<this.a.length;b++)a.push(this.b[this.a[b]]);return a};g.s=function(){D(this);return this.a.concat()};
g.zb=function(a){for(var b=0;b<this.a.length;b++){var c=this.a[b];if(E(this.b,c)&&this.b[c]==a)return!0}return!1};g.Ab=function(a,b){if(this===a)return!0;if(this.c!=a.c)return!1;b=b||sb;D(this);for(var c,d=0;c=this.a[d];d++)if(!b(this.get(c),a.get(c)))return!1;return!0};function sb(a,b){return a===b}g.Bb=function(){return 0==this.c};g.yb=function(){this.b={};this.f=this.c=this.a.length=0};
function D(a){if(a.c!=a.a.length){for(var b=0,c=0;b<a.a.length;){var d=a.a[b];E(a.b,d)&&(a.a[c++]=d);b++}a.a.length=c}if(a.c!=a.a.length){var e={};for(c=b=0;b<a.a.length;)d=a.a[b],E(e,d)||(a.a[c++]=d,e[d]=1),b++;a.a.length=c}}g.get=function(a,b){return E(this.b,a)?this.b[a]:b};g.set=function(a,b){E(this.b,a)||(this.c++,this.a.push(a),this.f++);this.b[a]=b};g.forEach=function(a,b){for(var c=this.s(),d=0;d<c.length;d++){var e=c[d],f=this.get(e);a.call(b,f,e,this)}};
g.kc=function(){for(var a=new rb,b=0;b<this.a.length;b++){var c=this.a[b];a.set(this.b[c],c)}return a};g.jc=function(){D(this);for(var a={},b=0;b<this.a.length;b++){var c=this.a[b];a[c]=this.b[c]}return a};g.Ba=function(){return tb(this,!0)};g.Ua=function(){return tb(this,!1)};function tb(a,b){D(a);var c=0,d=a.f,e=new qb;e.next=function(){if(d!=a.f)throw Error("The map has changed since the iterator was created");if(c>=a.a.length)throw pb;var f=a.a[c++];return b?f:a.b[f]};return e}
function E(a,b){return Object.prototype.hasOwnProperty.call(a,b)};function ub(a){if(a.h&&"function"==typeof a.h)return a.h();if("string"===typeof a)return a.split("");if(xa(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}b=[];c=0;for(d in a)b[c++]=a[d];return b}
function vb(a,b,c){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,c);else if(xa(a)||"string"===typeof a)Oa(a,b,c);else{if(a.s&&"function"==typeof a.s)var d=a.s();else if(a.h&&"function"==typeof a.h)d=void 0;else if(xa(a)||"string"===typeof a){d=[];for(var e=a.length,f=0;f<e;f++)d.push(f)}else for(f in d=[],e=0,a)d[e++]=f;e=ub(a);f=e.length;for(var h=0;h<f;h++)b.call(c,e[h],d&&d[h],a)}};var wb=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^/?#]*)@)?([^/#?]*?)(?::([0-9]+))?(?=[/\\#?]|$))?([^?#]+)?(?:\?([^#]*))?(?:#([\s\S]*))?$/;function xb(a,b){if(a){a=a.split("&");for(var c=0;c<a.length;c++){var d=a[c].indexOf("="),e=null;if(0<=d){var f=a[c].substring(0,d);e=a[c].substring(d+1)}else f=a[c];b(f,e?decodeURIComponent(e.replace(/\+/g," ")):"")}}};function yb(a){this.b=this.m=this.j="";this.f=null;this.l=this.c="";this.i=this.A=!1;if(a instanceof yb){this.i=a.i;zb(this,a.j);var b=a.m;F(this);this.m=b;b=a.b;F(this);this.b=b;Ab(this,a.f);b=a.c;F(this);this.c=b;Bb(this,Cb(a.a));a=a.l;F(this);this.l=a}else a&&(b=String(a).match(wb))?(this.i=!1,zb(this,b[1]||"",!0),a=b[2]||"",F(this),this.m=G(a),a=b[3]||"",F(this),this.b=G(a,!0),Ab(this,b[4]),a=b[5]||"",F(this),this.c=G(a,!0),Bb(this,b[6]||"",!0),a=b[7]||"",F(this),this.l=G(a)):(this.i=!1,this.a=
new Db(null,this.i))}g=yb.prototype;g.toString=function(){var a=[],b=this.j;b&&a.push(Eb(b,Fb,!0),":");var c=this.b;if(c||"file"==b)a.push("//"),(b=this.m)&&a.push(Eb(b,Fb,!0),"@"),a.push(encodeURIComponent(String(c)).replace(/%25([0-9a-fA-F]{2})/g,"%$1")),c=this.f,null!=c&&a.push(":",String(c));if(c=this.c)this.b&&"/"!=c.charAt(0)&&a.push("/"),a.push(Eb(c,"/"==c.charAt(0)?Gb:Hb,!0));(c=this.a.toString())&&a.push("?",c);(c=this.l)&&a.push("#",Eb(c,Ib));return a.join("")};
g.bb=function(a){var b=new yb(this),c=!!a.j;c?zb(b,a.j):c=!!a.m;if(c){var d=a.m;F(b);b.m=d}else c=!!a.b;c?(d=a.b,F(b),b.b=d):c=null!=a.f;d=a.c;if(c)Ab(b,a.f);else if(c=!!a.c){if("/"!=d.charAt(0))if(this.b&&!this.c)d="/"+d;else{var e=b.c.lastIndexOf("/");-1!=e&&(d=b.c.substr(0,e+1)+d)}e=d;if(".."==e||"."==e)d="";else if(x(e,"./")||x(e,"/.")){d=0==e.lastIndexOf("/",0);e=e.split("/");for(var f=[],h=0;h<e.length;){var k=e[h++];"."==k?d&&h==e.length&&f.push(""):".."==k?((1<f.length||1==f.length&&""!=f[0])&&
f.pop(),d&&h==e.length&&f.push("")):(f.push(k),d=!0)}d=f.join("/")}else d=e}c?(F(b),b.c=d):c=""!==a.a.toString();c?Bb(b,Cb(a.a)):c=!!a.l;c&&(a=a.l,F(b),b.l=a);return b};function zb(a,b,c){F(a);a.j=c?G(b,!0):b;a.j&&(a.j=a.j.replace(/:$/,""))}function Ab(a,b){F(a);if(b){b=Number(b);if(isNaN(b)||0>b)throw Error("Bad port number "+b);a.f=b}else a.f=null}function Bb(a,b,c){F(a);b instanceof Db?(a.a=b,Jb(a.a,a.i)):(c||(b=Eb(b,Kb)),a.a=new Db(b,a.i));return a}g.fc=function(a,b){return Bb(this,a,b)};
g.oa=function(){return G(this.a.toString())};g.dc=function(a,b){F(this);Array.isArray(b)||(b=[String(b)]);Lb(this.a,a,b);return this};g.Ma=function(a){return this.a.h(a)};g.Cb=function(a){return(!this.b&&!a.b||this.b==a.b)&&(null==this.f&&null==a.f||this.f==a.f)};g.Sb=function(){F(this);var a=Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^za()).toString(36);F(this);this.a.set("zx",a);return this};g.ab=function(a){F(this);Mb(this.a,a);return this};
g.hc=function(a){this.A=a;return this};g.Mb=function(){return this.A};function F(a){if(a.A)throw Error("Tried to modify a read-only Uri");}g.cb=function(a){this.i=a;this.a&&Jb(this.a,a);return this};function G(a,b){return a?b?decodeURI(a.replace(/%25/g,"%2525")):decodeURIComponent(a):""}function Eb(a,b,c){return"string"===typeof a?(a=encodeURI(a).replace(b,Nb),c&&(a=a.replace(/%25([0-9a-fA-F]{2})/g,"%$1")),a):null}
function Nb(a){a=a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)}var Fb=/[#\/\?@]/g,Hb=/[#\?:]/g,Gb=/[#\?]/g,Kb=/[#\?@]/g,Ib=/#/g;function Db(a,b){this.b=this.a=null;this.c=a||null;this.f=!!b}function H(a){a.a||(a.a=new rb,a.b=0,a.c&&xb(a.c,function(b,c){a.add(decodeURIComponent(b.replace(/\+/g," ")),c)}))}g=Db.prototype;g.Za=function(){H(this);return this.b};g.add=function(a,b){H(this);this.c=null;a=I(this,a);var c=this.a.get(a);c||this.a.set(a,c=[]);c.push(b);this.b+=1;return this};
function Mb(a,b){H(a);b=I(a,b);E(a.a.b,b)&&(a.c=null,a.b-=a.a.get(b).length,a=a.a,E(a.b,b)&&(delete a.b[b],a.c--,a.f++,a.a.length>2*a.c&&D(a)))}g.Wa=function(){this.a=this.c=null;this.b=0};g.$a=function(){H(this);return 0==this.b};function Ob(a,b){H(a);b=I(a,b);return E(a.a.b,b)}g.Xa=function(a){var b=this.h();return 0<=z(b,a)};g.forEach=function(a,b){H(this);this.a.forEach(function(c,d){Oa(c,function(e){a.call(b,e,d,this)},this)},this)};
g.s=function(){H(this);for(var a=this.a.h(),b=this.a.s(),c=[],d=0;d<b.length;d++)for(var e=a[d],f=0;f<e.length;f++)c.push(b[d]);return c};g.h=function(a){H(this);var b=[];if("string"===typeof a)Ob(this,a)&&(b=Qa(b,this.a.get(I(this,a))));else{a=this.a.h();for(var c=0;c<a.length;c++)b=Qa(b,a[c])}return b};g.set=function(a,b){H(this);this.c=null;a=I(this,a);Ob(this,a)&&(this.b-=this.a.get(a).length);this.a.set(a,[b]);this.b+=1;return this};
g.get=function(a,b){if(!a)return b;a=this.h(a);return 0<a.length?String(a[0]):b};function Lb(a,b,c){Mb(a,b);0<c.length&&(a.c=null,a.a.set(I(a,b),Ra(c)),a.b+=c.length)}g.toString=function(){if(this.c)return this.c;if(!this.a)return"";for(var a=[],b=this.a.s(),c=0;c<b.length;c++){var d=b[c],e=encodeURIComponent(String(d));d=this.h(d);for(var f=0;f<d.length;f++){var h=e;""!==d[f]&&(h+="="+encodeURIComponent(String(d[f])));a.push(h)}}return this.c=a.join("&")};
g.ca=function(a){H(this);this.a.forEach(function(b,c){0<=z(a,c)||Mb(this,c)},this);return this};function Cb(a){var b=new Db;b.c=a.c;a.a&&(b.a=new rb(a.a),b.b=a.b);return b}function I(a,b){b=String(b);a.f&&(b=b.toLowerCase());return b}function Jb(a,b){b&&!a.f&&(H(a),a.c=null,a.a.forEach(function(c,d){var e=d.toLowerCase();d!=e&&(Mb(this,d),Lb(this,e,c))},a));a.f=b}g.Ya=function(a){for(var b=0;b<arguments.length;b++)vb(arguments[b],function(c,d){this.add(d,c)},this)};var Pb={},Qb={},Rb={};function J(){throw Error("Do not instantiate directly");}J.prototype.J=null;J.prototype.toString=function(){return this.O};J.prototype.a=function(){if(this.K!==Qb)throw Error("Sanitized content was not of kind URI.");return new B(ab,this.toString())};function Sb(){J.call(this)}Aa(Sb,J);Sb.prototype.K=Pb;function K(a,b){return null!=a&&a.K===b};function Tb(a){Tb[" "](a);return a}Tb[" "]=wa;function Ub(a,b){var c=Vb;return Object.prototype.hasOwnProperty.call(c,a)?c[a]:c[a]=b(a)};var Wb=x(y,"Opera"),L=x(y,"Trident")||x(y,"MSIE"),Xb=x(y,"Edge"),Yb=x(y,"Gecko")&&!(x(y.toLowerCase(),"webkit")&&!x(y,"Edge"))&&!(x(y,"Trident")||x(y,"MSIE"))&&!x(y,"Edge"),M=x(y.toLowerCase(),"webkit")&&!x(y,"Edge"),Zb=x(y,"Macintosh");function $b(){var a=u.document;return a?a.documentMode:void 0}var ac;
a:{var bc="",cc=function(){var a=y;if(Yb)return/rv:([^\);]+)(\)|;)/.exec(a);if(Xb)return/Edge\/([\d\.]+)/.exec(a);if(L)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(M)return/WebKit\/(\S+)/.exec(a);if(Wb)return/(?:Version)[ \/]?(\S+)/.exec(a)}();cc&&(bc=cc?cc[1]:"");if(L){var dc=$b();if(null!=dc&&dc>parseFloat(bc)){ac=String(dc);break a}}ac=bc}var ec=ac,Vb={};
function O(a){return Ub(a,function(){for(var b=0,c=Ba(String(ec)).split("."),d=Ba(String(a)).split("."),e=Math.max(c.length,d.length),f=0;0==b&&f<e;f++){var h=c[f]||"",k=d[f]||"";do{h=/(\d*)(\D*)(.*)/.exec(h)||["","","",""];k=/(\d*)(\D*)(.*)/.exec(k)||["","","",""];if(0==h[0].length&&0==k[0].length)break;b=Ka(0==h[1].length?0:parseInt(h[1],10),0==k[1].length?0:parseInt(k[1],10))||Ka(0==h[2].length,0==k[2].length)||Ka(h[2],k[2]);h=h[3];k=k[3]}while(0==b)}return 0<=b})}var P;P=u.document&&L?$b():void 0;function fc(a){if(null!=a)switch(a.J){case 1:return 1;case -1:return-1;case 0:return 0}return null}function gc(a){return K(a,Pb)?a:a instanceof C?hc(eb(a).toString(),a.v()):hc(ob(String(String(a))),fc(a))}var hc=function(a){function b(c){this.O=c}b.prototype=a.prototype;return function(c,d){c=new b(String(c));void 0!==d&&(c.J=d);return c}}(Sb);function ic(a){return K(a,Pb)?String(String(a.O).replace(jc,"").replace(kc,"&lt;")).replace(lc,mc):ob(String(a))}
function nc(a){K(a,Qb)||K(a,Rb)?a=Q(a):a instanceof B?a=Q(cb(a)):a instanceof A?a=Q(Ya(a).toString()):(a=String(a),a=oc.test(a)?a.replace(pc,qc):"about:invalid#zSoyz");return a}var rc={"\x00":"&#0;","\t":"&#9;","\n":"&#10;","\x0B":"&#11;","\f":"&#12;","\r":"&#13;"," ":"&#32;",'"':"&quot;","&":"&amp;","'":"&#39;","-":"&#45;","/":"&#47;","<":"&lt;","=":"&#61;",">":"&gt;","`":"&#96;","\u0085":"&#133;","\u00a0":"&#160;","\u2028":"&#8232;","\u2029":"&#8233;"};function mc(a){return rc[a]}
var sc={"\x00":"%00","\u0001":"%01","\u0002":"%02","\u0003":"%03","\u0004":"%04","\u0005":"%05","\u0006":"%06","\u0007":"%07","\b":"%08","\t":"%09","\n":"%0A","\x0B":"%0B","\f":"%0C","\r":"%0D","\u000e":"%0E","\u000f":"%0F","\u0010":"%10","\u0011":"%11","\u0012":"%12","\u0013":"%13","\u0014":"%14","\u0015":"%15","\u0016":"%16","\u0017":"%17","\u0018":"%18","\u0019":"%19","\u001a":"%1A","\u001b":"%1B","\u001c":"%1C","\u001d":"%1D","\u001e":"%1E","\u001f":"%1F"," ":"%20",'"':"%22","'":"%27","(":"%28",
")":"%29","<":"%3C",">":"%3E","\\":"%5C","{":"%7B","}":"%7D","\u007f":"%7F","\u0085":"%C2%85","\u00a0":"%C2%A0","\u2028":"%E2%80%A8","\u2029":"%E2%80%A9","\uff01":"%EF%BC%81","\uff03":"%EF%BC%83","\uff04":"%EF%BC%84","\uff06":"%EF%BC%86","\uff07":"%EF%BC%87","\uff08":"%EF%BC%88","\uff09":"%EF%BC%89","\uff0a":"%EF%BC%8A","\uff0b":"%EF%BC%8B","\uff0c":"%EF%BC%8C","\uff0f":"%EF%BC%8F","\uff1a":"%EF%BC%9A","\uff1b":"%EF%BC%9B","\uff1d":"%EF%BC%9D","\uff1f":"%EF%BC%9F","\uff20":"%EF%BC%A0","\uff3b":"%EF%BC%BB",
"\uff3d":"%EF%BC%BD"};function qc(a){return sc[a]}var lc=/[\x00\x22\x27\x3c\x3e]/g,pc=/[\x00- \x22\x27-\x29\x3c\x3e\\\x7b\x7d\x7f\x85\xa0\u2028\u2029\uff01\uff03\uff04\uff06-\uff0c\uff0f\uff1a\uff1b\uff1d\uff1f\uff20\uff3b\uff3d]/g,oc=/^(?![^#?]*\/(?:\.|%2E){2}(?:[\/?#]|$))(?:(?:https?|mailto):|[^&:\/?#]*(?:[\/?#]|$))/i,tc=/^[^&:\/?#]*(?:[\/?#]|$)|^https?:|^data:image\/[a-z0-9+]+;base64,[a-z0-9+\/]+=*$|^blob:/i;function Q(a){return String(a).replace(pc,qc)}
var jc=/<(?:!|\/?([a-zA-Z][a-zA-Z0-9:\-]*))(?:[^>'"]|"[^"]*"|'[^']*')*>/g,kc=/</g;var uc=!L||9<=Number(P),vc=!Yb&&!L||L&&9<=Number(P)||Yb&&O("1.9.1"),wc=L&&!O("9"),xc=L||Wb||M;function R(a,b){this.x=void 0!==a?a:0;this.a=void 0!==b?b:0}g=R.prototype;g.sb=function(){return new R(this.x,this.a)};g.tb=function(a){return a instanceof R&&(this==a?!0:this&&a?this.x==a.x&&this.a==a.a:!1)};g.ceil=function(){this.x=Math.ceil(this.x);this.a=Math.ceil(this.a);return this};g.floor=function(){this.x=Math.floor(this.x);this.a=Math.floor(this.a);return this};g.round=function(){this.x=Math.round(this.x);this.a=Math.round(this.a);return this};
g.vb=function(a,b){a instanceof R?(this.x+=a.x,this.a+=a.a):(this.x+=Number(a),"number"===typeof b&&(this.a+=b));return this};g.ub=function(a,b){this.x*=a;this.a*="number"===typeof b?b:a;return this};g.Xb=function(a,b){a=a*Math.PI/180;b=b||new R(0,0);var c=this.x,d=this.a,e=Math.cos(a);a=Math.sin(a);this.x=(c-b.x)*e-(d-b.a)*a+b.x;this.a=(c-b.x)*a+(d-b.a)*e+b.a};function yc(a,b){this.width=a;this.height=b}g=yc.prototype;g.wb=function(){return new yc(this.width,this.height)};g.Ea=function(){return Math.max(this.width,this.height)};g.Sa=function(){return Math.min(this.width,this.height)};g.Tb=function(){return 2*(this.width+this.height)};g.aspectRatio=function(){return this.width/this.height};g.xb=function(){return!(this.width*this.height)};g.ceil=function(){this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};
g.ga=function(a){return this.width<=a.width&&this.height<=a.height};g.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};g.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};function zc(a,b){a.width*=b;a.height*=b;return a}g.$b=function(a){a=this.aspectRatio()<=a.aspectRatio()?a.width/this.width:a.height/this.height;return zc(this,a)};
g.ac=function(a){a=this.aspectRatio()>a.aspectRatio()?a.width/this.width:a.height/this.height;return zc(this,a)};function Ac(a){return a?new S(T(a)):Na||(Na=new S)}function Bc(a,b){var c=b||document,d=null;c.getElementsByClassName?d=c.getElementsByClassName(a)[0]:d=Cc(document,"*",a,b);return d||null}
function Dc(a,b,c,d){a=d||a;var e=b&&"*"!=b?String(b).toUpperCase():"";if(a.querySelectorAll&&a.querySelector&&(e||c))return a.querySelectorAll(e+(c?"."+c:""));if(c&&a.getElementsByClassName){b=a.getElementsByClassName(c);if(e){a={};for(var f=d=0,h;h=b[f];f++)e==h.nodeName&&(a[d++]=h);a.length=d;return a}return b}b=a.getElementsByTagName(e||"*");if(c){a={};for(f=d=0;h=b[f];f++){e=h.className;var k;if(k="function"==typeof e.split)k=0<=z(e.split(/\s+/),c);k&&(a[d++]=h)}a.length=d;return a}return b}
function Cc(a,b,c,d){var e=d||a,f=b&&"*"!=b?String(b).toUpperCase():"";return e.querySelectorAll&&e.querySelector&&(f||c)?e.querySelector(f+(c?"."+c:"")):Dc(a,b,c,d)[0]||null}function Ec(a,b){Sa(b,function(c,d){c&&"object"==typeof c&&c.G&&(c=c.D());"style"==d?a.style.cssText=c:"class"==d?a.className=c:"for"==d?a.htmlFor=c:Fc.hasOwnProperty(d)?a.setAttribute(Fc[d],c):0==d.lastIndexOf("aria-",0)||0==d.lastIndexOf("data-",0)?a.setAttribute(d,c):a[d]=c})}
var Fc={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",nonce:"nonce",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"};function Gc(a){a=a.document;a=Hc(a)?a.documentElement:a.body;return new yc(a.clientWidth,a.clientHeight)}function Ic(a){return a.scrollingElement?a.scrollingElement:!M&&Hc(a)?a.documentElement:a.body||a.documentElement}
function Jc(a){return a.parentWindow||a.defaultView}function Kc(a,b,c,d){function e(h){h&&b.appendChild("string"===typeof h?a.createTextNode(h):h)}for(;d<c.length;d++){var f=c[d];xa(f)&&!Lc(f)?Oa(Mc(f)?Ra(f):f,e):e(f)}}function U(a,b){b=String(b);"application/xhtml+xml"===a.contentType&&(b=b.toLowerCase());return a.createElement(b)}function Hc(a){return"CSS1Compat"==a.compatMode}function Nc(a){for(var b;b=a.firstChild;)a.removeChild(b)}
function Oc(a){return a&&a.parentNode?a.parentNode.removeChild(a):null}function Pc(a,b){for(;a&&1!=a.nodeType;)a=b?a.nextSibling:a.previousSibling;return a}function Lc(a){return w(a)&&0<a.nodeType}function Qc(a){return w(a)&&1==a.nodeType}function Rc(a,b){if(!a||!b)return!1;if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||!!(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a}
function Sc(a,b){var c=a.parentNode;if(c==b)return-1;for(;b.parentNode!=c;)b=b.parentNode;return Tc(b,a)}function Tc(a,b){for(;b=b.previousSibling;)if(b==a)return-1;return 1}function T(a){return 9==a.nodeType?a:a.ownerDocument||a.document}
function Uc(a,b){if("textContent"in a)a.textContent=b;else if(3==a.nodeType)a.data=String(b);else if(a.firstChild&&3==a.firstChild.nodeType){for(;a.lastChild!=a.firstChild;)a.removeChild(a.lastChild);a.firstChild.data=String(b)}else Nc(a),a.appendChild(T(a).createTextNode(String(b)))}function Vc(a,b,c,d){if(null!=a)for(a=a.firstChild;a;){if(b(a)&&(c.push(a),d)||Vc(a,b,c,d))return!0;a=a.nextSibling}return!1}var Wc={SCRIPT:1,STYLE:1,HEAD:1,IFRAME:1,OBJECT:1},Xc={IMG:" ",BR:"\n"};
function Yc(a){return Zc(a)&&$c(a)}function Zc(a){return L&&!O("9")?(a=a.getAttributeNode("tabindex"),null!=a&&a.specified):a.hasAttribute("tabindex")}function $c(a){a=a.tabIndex;return"number"===typeof a&&0<=a&&32768>a}function ad(a){if(wc&&null!==a&&"innerText"in a)a=a.innerText.replace(/(\r\n|\r|\n)/g,"\n");else{var b=[];bd(a,b,!0);a=b.join("")}a=a.replace(/ \xAD /g," ").replace(/\xAD/g,"");a=a.replace(/\u200B/g,"");wc||(a=a.replace(/ +/g," "));" "!=a&&(a=a.replace(/^\s*/,""));return a}
function bd(a,b,c){if(!(a.nodeName in Wc))if(3==a.nodeType)c?b.push(String(a.nodeValue).replace(/(\r\n|\r|\n)/g,"")):b.push(a.nodeValue);else if(a.nodeName in Xc)b.push(Xc[a.nodeName]);else for(a=a.firstChild;a;)bd(a,b,c),a=a.nextSibling}function Mc(a){if(a&&"number"==typeof a.length){if(w(a))return"function"==typeof a.item||"string"==typeof a.item;if("function"==v(a))return"function"==typeof a.item}return!1}
function cd(a,b,c,d){if(!b&&!c)return null;var e=b?String(b).toUpperCase():null;return dd(a,function(f){var h;(h=!e||f.nodeName==e)&&!(h=!c)&&(h="string"===typeof f.className)&&(h=0<=z(f.className.split(/\s+/),c));return h},!0,d)}function dd(a,b,c,d){a&&!c&&(a=a.parentNode);for(c=0;a&&(null==d||c<=d);){if(b(a))return a;a=a.parentNode;c++}return null}function S(a){this.a=a||u.document||document}g=S.prototype;g.ua=Ac;g.bc=function(a){this.a=a};g.qa=function(){return this.a};
g.S=function(a){return"string"===typeof a?this.a.getElementById(a):a};g.Qa=function(a){return"string"===typeof a?this.a.getElementById(a):a};g.W=S.prototype.S;g.jb=function(a,b){return(b||this.a).getElementsByTagName(String(a))};g.T=function(a,b,c){return Dc(this.a,a,b,c)};g.wa=function(a,b,c){return Cc(this.a,a,b,c)};g.xa=function(a,b){var c=(b=b||this.a)||document;return c.querySelectorAll&&c.querySelector?c.querySelectorAll("."+a):Dc(document,"*",a,b)};g.va=function(a,b){return Bc(a,b||this.a)};
g.Ra=function(a,b){return Bc(a,b||this.a)};g.X=S.prototype.T;g.ec=Ec;g.Va=function(a){return Gc(a||Jc(this.a)||window)};g.ra=function(){var a=Jc(this.a),b=a.document;var c=0;if(b){c=b.body;var d=b.documentElement;if(d&&c)if(a=Gc(a).height,Hc(b)&&d.scrollHeight)c=d.scrollHeight!=a?d.scrollHeight:d.offsetHeight;else{b=d.scrollHeight;var e=d.offsetHeight;d.clientHeight!=e&&(b=c.scrollHeight,e=c.offsetHeight);c=b>a?b>e?b:e:b<e?b:e}else c=0}return c};
g.R=function(a,b,c){var d=this.a,e=arguments,f=String(e[0]),h=e[1];if(!uc&&h&&(h.name||h.type)){f=["<",f];h.name&&f.push(' name="',ob(h.name),'"');if(h.type){f.push(' type="',ob(h.type),'"');var k={};Va(k,h);delete k.type;h=k}f.push(">");f=f.join("")}f=U(d,f);h&&("string"===typeof h?f.className=h:Array.isArray(h)?f.className=h.join(" "):Ec(f,h));2<e.length&&Kc(d,f,e,2);return f};g.Y=S.prototype.R;g.ib=function(a){return this.a.createTextNode(String(a))};
g.ba=function(a,b,c){var d=this.a;c=!!c;for(var e=U(d,"TABLE"),f=e.appendChild(U(d,"TBODY")),h=0;h<a;h++){for(var k=U(d,"TR"),l=0;l<b;l++){var m=U(d,"TD");c&&Uc(m,"\u00a0");k.appendChild(m)}f.appendChild(k)}return e};g.Zb=function(a){var b=this.a;var c=U(b,"DIV");L?(a=jb(lb,a),nb(c,a),c.removeChild(c.firstChild)):nb(c,a);if(1==c.childNodes.length)c=c.removeChild(c.firstChild);else{for(b=b.createDocumentFragment();c.firstChild;)b.appendChild(c.firstChild);c=b}return c};g.Gb=function(){return Hc(this.a)};
g.ta=function(){return Ic(this.a)};g.sa=function(){var a=this.a,b=Ic(a);a=Jc(a);return L&&O("10")&&a.pageYOffset!=b.scrollTop?new R(b.scrollLeft,b.scrollTop):new R(a.pageXOffset||b.scrollLeft,a.pageYOffset||b.scrollTop)};g.ia=function(a){a=a||this.a;try{var b=a&&a.activeElement;var c=b&&b.nodeName?b:null}catch(d){c=null}return c};g.fb=function(a,b){a.appendChild(b)};g.eb=function(a,b){Kc(T(a),a,arguments,1)};g.gb=function(a){if(1!=a.nodeType)return!1;switch(a.tagName){case "APPLET":case "AREA":case "BASE":case "BR":case "COL":case "COMMAND":case "EMBED":case "FRAME":case "HR":case "IMG":case "INPUT":case "IFRAME":case "ISINDEX":case "KEYGEN":case "LINK":case "NOFRAMES":case "NOSCRIPT":case "META":case "OBJECT":case "PARAM":case "SCRIPT":case "SOURCE":case "STYLE":case "TRACK":case "WBR":return!1}return!0};
g.Wb=Nc;g.Fb=function(a,b){b.parentNode&&b.parentNode.insertBefore(a,b)};g.Eb=function(a,b){b.parentNode&&b.parentNode.insertBefore(a,b.nextSibling)};g.Db=function(a,b,c){a.insertBefore(b,a.childNodes[c]||null)};g.kb=Oc;g.lb=function(a,b){var c=b.parentNode;c&&c.replaceChild(a,b)};g.ha=function(a){var b,c=a.parentNode;if(c&&11!=c.nodeType){if(a.removeNode)return a.removeNode(!1);for(;b=a.firstChild;)c.insertBefore(b,a);return Oc(a)}};
g.na=function(a){return vc&&void 0!=a.children?a.children:Pa(a.childNodes,function(b){return 1==b.nodeType})};g.ya=function(a){return void 0!==a.firstElementChild?a.firstElementChild:Pc(a.firstChild,!0)};g.Ca=function(a){return void 0!==a.lastElementChild?a.lastElementChild:Pc(a.lastChild,!1)};g.Fa=function(a){return void 0!==a.nextElementSibling?a.nextElementSibling:Pc(a.nextSibling,!0)};g.Oa=function(a){return void 0!==a.previousElementSibling?a.previousElementSibling:Pc(a.previousSibling,!1)};
g.Ga=function(a){if(!a)return null;if(a.firstChild)return a.firstChild;for(;a&&!a.nextSibling;)a=a.parentNode;return a?a.nextSibling:null};g.Pa=function(a){if(!a)return null;if(!a.previousSibling)return a.parentNode;for(a=a.previousSibling;a&&a.lastChild;)a=a.lastChild;return a};g.Kb=Lc;g.Hb=Qc;g.Nb=function(a){return w(a)&&a.window==a};g.Na=function(a){var b;if(xc&&!(L&&O("9")&&!O("10")&&u.SVGElement&&a instanceof u.SVGElement)&&(b=a.parentElement))return b;b=a.parentNode;return Qc(b)?b:null};
g.hb=Rc;
g.aa=function(a,b){if(a==b)return 0;if(a.compareDocumentPosition)return a.compareDocumentPosition(b)&2?1:-1;if(L&&!(9<=Number(P))){if(9==a.nodeType)return-1;if(9==b.nodeType)return 1}if("sourceIndex"in a||a.parentNode&&"sourceIndex"in a.parentNode){var c=1==a.nodeType,d=1==b.nodeType;if(c&&d)return a.sourceIndex-b.sourceIndex;var e=a.parentNode,f=b.parentNode;return e==f?Tc(a,b):!c&&Rc(e,b)?-1*Sc(a,b):!d&&Rc(f,a)?Sc(b,a):(c?a.sourceIndex:e.sourceIndex)-(d?b.sourceIndex:f.sourceIndex)}d=T(a);c=d.createRange();
c.selectNode(a);c.collapse(!0);a=d.createRange();a.selectNode(b);a.collapse(!0);return c.compareBoundaryPoints(u.Range.START_TO_END,a)};g.da=function(a){var b,c=arguments.length;if(!c)return null;if(1==c)return arguments[0];var d=[],e=Infinity;for(b=0;b<c;b++){for(var f=[],h=arguments[b];h;)f.unshift(h),h=h.parentNode;d.push(f);e=Math.min(e,f.length)}f=null;for(b=0;b<e;b++){h=d[0][b];for(var k=1;k<c;k++)if(h!=d[k][b])return f;f=h}return f};g.La=T;g.za=function(a){return a.contentDocument||a.contentWindow.document};
g.Aa=function(a){try{var b;if(!(b=a.contentWindow)){if(a.contentDocument){var c=a.contentDocument;var d=c?Jc(c):window}else d=null;b=d}return b}catch(e){}return null};g.ic=Uc;g.Ka=function(a){if("outerHTML"in a)return a.outerHTML;var b=U(T(a),"DIV");b.appendChild(a.cloneNode(!0));return b.innerHTML};g.ea=function(a,b){var c=[];return Vc(a,b,c,!0)?c[0]:void 0};g.fa=function(a,b){var c=[];Vc(a,b,c,!1);return c};g.Jb=Yc;g.cc=function(a,b){b?a.tabIndex=0:(a.tabIndex=-1,a.removeAttribute("tabIndex"))};
g.Ib=function(a){var b;if((b="A"==a.tagName&&a.hasAttribute("href")||"INPUT"==a.tagName||"TEXTAREA"==a.tagName||"SELECT"==a.tagName||"BUTTON"==a.tagName?!a.disabled&&(!Zc(a)||$c(a)):Yc(a))&&L){var c;"function"!=v(a.getBoundingClientRect)||L&&null==a.parentElement?c={height:a.offsetHeight,width:a.offsetWidth}:c=a.getBoundingClientRect();a=null!=c&&0<c.height&&0<c.width}else a=b;return a};g.Ta=ad;g.Ia=function(a){return ad(a).length};
g.Ja=function(a,b){b=b||T(a).body;for(var c=[];a&&a!=b;){for(var d=a;d=d.previousSibling;)c.unshift(ad(d));a=a.parentNode}return c.join("").replace(/^[\s\xa0]+/,"").replace(/ +/g," ").length};
g.Ha=function(a,b,c){a=[a];for(var d=0,e=null;0<a.length&&d<b;)if(e=a.pop(),!(e.nodeName in Wc))if(3==e.nodeType){var f=e.nodeValue.replace(/(\r\n|\r|\n)/g,"").replace(/ +/g," ");d+=f.length}else if(e.nodeName in Xc)d+=Xc[e.nodeName].length;else for(f=e.childNodes.length-1;0<=f;f--)a.push(e.childNodes[f]);w(c)&&(c.Vb=e?e.nodeValue.length+b-d-1:0,c.node=e);return e};g.Lb=Mc;g.la=cd;g.ka=function(a,b,c){return cd(a,null,b,c)};g.ja=dd;g.ma=function(a){return a.getContext("2d")};function ed(a){var b=new URL(document.location.toString());a=new URL(a,b.origin);if(a.hostname!==b.hostname)return a;var c=new yb(b.href),d=new yb(a.href);"tenant hl authuser acting_user mv mh skip_cache".split(" ").forEach(function(e){var f=c.a.get(e);f&&!d.a.get(e)&&(F(d),d.a.set(e,f))});a.search=d.a.toString();return a};var fd=!/^\s*class\s*\{\s*\}\s*$/.test(function(){}.toString());/*

 Copyright (c) 2016 The Polymer Project Authors. All rights reserved.
 This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
 The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
 The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
 Code distributed by Google as part of the polymer project is also
 subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
(function(){if(fd&&!HTMLElement.es5Shimmed&&void 0!==window.Reflect&&void 0!==window.customElements&&!window.customElements.polyfillWrapFlushCallback){var a=HTMLElement;window.HTMLElement=function(){return Reflect.construct(a,[],this.constructor)};HTMLElement.prototype=a.prototype;HTMLElement.prototype.constructor=HTMLElement;HTMLElement.es5Shimmed=!0;Object.setPrototypeOf(HTMLElement,a)}})();function V(a){var b=HTMLElement.call(this)||this;a&&("string"===typeof a&&(a=[a]),document.body.dispatchEvent(new CustomEvent("devsite-load-custom-elements",{bubbles:!0,detail:a})));return b}ia(V,HTMLElement);V.prototype.V=function(){console.warn(this.tagName,"has not implemented update")};V.prototype.j=function(a){a=void 0===a?"":a;return document.createRange().createContextualFragment(a||"")};
V.prototype.A=function(a,b,c){a&&b?a.parentNode.replaceChild(document.importNode(b,!0),a):!b&&a?a.parentNode.removeChild(a):!a&&b&&(c?(a=document.importNode(b,!0),c.parentElement.insertBefore(a,c.nextSibling)):this.appendChild(document.importNode(b,!0)))};var gd=!L||9<=Number(P),hd=!L||9<=Number(P),id=L&&!O("9"),jd=function(){if(!u.addEventListener||!Object.defineProperty)return!1;var a=!1,b=Object.defineProperty({},"passive",{get:function(){a=!0}});try{u.addEventListener("test",wa,b),u.removeEventListener("test",wa,b)}catch(c){}return a}();function kd(){this.u=this.u;this.b=this.b}g=kd.prototype;g.u=!1;g.U=function(){return this.u};g.pa=kd.prototype.U;g.N=function(){this.u||(this.u=!0,this.L())};g.Ub=function(a){a=ya(ld,a);this.u?a():(this.b||(this.b=[]),this.b.push(a))};g.L=function(){if(this.b)for(;this.b.length;)this.b.shift()()};function ld(a){a&&"function"==typeof a.N&&a.N()};function md(a,b){this.type=a;this.w=this.target=b;this.m=this.b=!1}md.prototype.F=function(){this.b=!0};md.prototype.B=function(){this.m=!0};function W(a,b){md.call(this,a?a.type:"");this.relatedTarget=this.w=this.target=null;this.button=this.screenY=this.screenX=this.clientY=this.clientX=this.j=this.i=0;this.key="";this.c=this.f=0;this.metaKey=this.shiftKey=this.altKey=this.ctrlKey=!1;this.l=null;this.A=!1;this.pointerId=0;this.pointerType="";this.a=null;if(a){var c=this.type=a.type,d=a.changedTouches&&a.changedTouches.length?a.changedTouches[0]:null;this.target=a.target||a.srcElement;this.w=b;if(b=a.relatedTarget){if(Yb){a:{try{Tb(b.nodeName);
var e=!0;break a}catch(f){}e=!1}e||(b=null)}}else"mouseover"==c?b=a.fromElement:"mouseout"==c&&(b=a.toElement);this.relatedTarget=b;d?(this.clientX=void 0!==d.clientX?d.clientX:d.pageX,this.clientY=void 0!==d.clientY?d.clientY:d.pageY,this.screenX=d.screenX||0,this.screenY=d.screenY||0):(this.i=M||void 0!==a.offsetX?a.offsetX:a.layerX,this.j=M||void 0!==a.offsetY?a.offsetY:a.layerY,this.clientX=void 0!==a.clientX?a.clientX:a.pageX,this.clientY=void 0!==a.clientY?a.clientY:a.pageY,this.screenX=a.screenX||
0,this.screenY=a.screenY||0);this.button=a.button;this.f=a.keyCode||0;this.key=a.key||"";this.c=a.charCode||("keypress"==c?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.A=Zb?a.metaKey:a.ctrlKey;this.pointerId=a.pointerId||0;this.pointerType="string"===typeof a.pointerType?a.pointerType:nd[a.pointerType]||"";this.l=a.state;this.a=a;a.defaultPrevented&&this.B()}}Aa(W,md);var od=[1,4,2],nd={2:"touch",3:"pen",4:"mouse"};
W.prototype.Yb=function(){return(gd?0==this.a.button:"click"==this.type?!0:!!(this.a.button&od[0]))&&!(M&&Zb&&this.ctrlKey)};W.prototype.F=function(){W.H.F.call(this);this.a.stopPropagation?this.a.stopPropagation():this.a.cancelBubble=!0};W.prototype.B=function(){W.H.B.call(this);var a=this.a;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,id)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};W.prototype.V=function(){return this.a};var pd="closure_listenable_"+(1E6*Math.random()|0),qd=0;function rd(a,b,c,d,e){this.listener=a;this.a=null;this.src=b;this.type=c;this.capture=!!d;this.b=e;this.key=++qd;this.C=this.I=!1}function sd(a){a.C=!0;a.listener=null;a.a=null;a.src=null;a.b=null};function td(a){this.src=a;this.a={};this.b=0}g=td.prototype;g.ob=function(){var a=0,b;for(b in this.a)a+=this.a[b].length;return a};g.add=function(a,b,c,d,e){var f=a.toString();a=this.a[f];a||(a=this.a[f]=[],this.b++);var h=ud(a,b,d,e);-1<h?(b=a[h],c||(b.I=!1)):(b=new rd(b,this.src,f,!!d,e),b.I=c,a.push(b));return b};
g.qb=function(a,b,c,d){a=a.toString();if(!(a in this.a))return!1;var e=this.a[a];b=ud(e,b,c,d);return-1<b?(sd(e[b]),Array.prototype.splice.call(e,b,1),0==e.length&&(delete this.a[a],this.b--),!0):!1};g.rb=function(a){a=a&&a.toString();var b=0,c;for(c in this.a)if(!a||c==a){for(var d=this.a[c],e=0;e<d.length;e++)++b,sd(d[e]);delete this.a[c];this.b--}return b};g.Da=function(a,b){a=this.a[a.toString()];var c=[];if(a)for(var d=0;d<a.length;++d){var e=a[d];e.capture==b&&c.push(e)}return c};
g.pb=function(a,b){var c=void 0!==a,d=c?a.toString():"",e=void 0!==b;return Ta(this.a,function(f){for(var h=0;h<f.length;++h)if(!(c&&f[h].type!=d||e&&f[h].capture!=b))return!0;return!1})};function ud(a,b,c,d){for(var e=0;e<a.length;++e){var f=a[e];if(!f.C&&f.listener==b&&f.capture==!!c&&f.b==d)return e}return-1};var vd="closure_lm_"+(1E6*Math.random()|0),wd={},xd=0;function yd(a,b,c,d,e){if(d&&d.once)return zd(a,b,c,d,e);if(Array.isArray(b)){for(var f=0;f<b.length;f++)yd(a,b[f],c,d,e);return null}c=Ad(c);return a&&a[pd]?Bd(a,b,c,w(d)?!!d.capture:!!d,e):Cd(a,b,c,!1,d,e)}
function Cd(a,b,c,d,e,f){if(!b)throw Error("Invalid event type");var h=w(e)?!!e.capture:!!e,k=Dd(a);k||(a[vd]=k=new td(a));c=k.add(b,c,d,h,f);if(c.a)return c;d=Ed();c.a=d;d.src=a;d.listener=c;if(a.addEventListener)jd||(e=h),void 0===e&&(e=!1),a.addEventListener(b.toString(),d,e);else if(a.attachEvent)a.attachEvent(Fd(b.toString()),d);else if(a.addListener&&a.removeListener)a.addListener(d);else throw Error("addEventListener and attachEvent are unavailable.");xd++;return c}
function Ed(){var a=Gd,b=hd?function(c){return a.call(b.src,b.listener,c)}:function(c){c=a.call(b.src,b.listener,c);if(!c)return c};return b}function zd(a,b,c,d,e){if(Array.isArray(b)){for(var f=0;f<b.length;f++)zd(a,b[f],c,d,e);return null}c=Ad(c);return a&&a[pd]?a.m(b,c,w(d)?!!d.capture:!!d,e):Cd(a,b,c,!0,d,e)}
function Hd(a){if("number"!==typeof a&&a&&!a.C){var b=a.src;if(b&&b[pd])b.a(a);else{var c=a.type,d=a.a;b.removeEventListener?b.removeEventListener(c,d,a.capture):b.detachEvent?b.detachEvent(Fd(c),d):b.addListener&&b.removeListener&&b.removeListener(d);xd--;if(c=Dd(b)){d=a.type;if(d in c.a){var e=c.a[d],f=z(e,a),h;(h=0<=f)&&Array.prototype.splice.call(e,f,1);h&&(sd(a),0==c.a[d].length&&(delete c.a[d],c.b--))}0==c.b&&(c.src=null,b[vd]=null)}else sd(a)}}}
function Fd(a){return a in wd?wd[a]:wd[a]="on"+a}function Id(a,b,c,d){var e=!0;if(a=Dd(a))if(b=a.a[b.toString()])for(b=b.concat(),a=0;a<b.length;a++){var f=b[a];f&&f.capture==c&&!f.C&&(f=Jd(f,d),e=e&&!1!==f)}return e}function Jd(a,b){var c=a.listener,d=a.b||a.src;a.I&&Hd(a);return c.call(d,b)}
function Gd(a,b){if(a.C)return!0;if(!hd){var c=b||va("window.event");b=new W(c,this);var d=!0;if(!(0>c.keyCode||void 0!=c.returnValue)){a:{var e=!1;if(0==c.keyCode)try{c.keyCode=-1;break a}catch(h){e=!0}if(e||void 0==c.returnValue)c.returnValue=!0}c=[];for(e=b.w;e;e=e.parentNode)c.push(e);a=a.type;for(e=c.length-1;!b.b&&0<=e;e--){b.w=c[e];var f=Id(c[e],a,!0,b);d=d&&f}for(e=0;!b.b&&e<c.length;e++)b.w=c[e],f=Id(c[e],a,!1,b),d=d&&f}return d}return Jd(a,new W(b,this))}
function Dd(a){a=a[vd];return a instanceof td?a:null}var Kd="__closure_events_fn_"+(1E9*Math.random()>>>0);function Ad(a){if("function"==v(a))return a;a[Kd]||(a[Kd]=function(b){return a.handleEvent(b)});return a[Kd]};function Ld(a){kd.call(this);this.c=a;this.a={}}Aa(Ld,kd);var Md=[];function Nd(a,b,c,d){Bd(a,b,c,d,void 0)}g=Ld.prototype;g.Pb=function(a,b,c,d,e){return Bd(this,a,b,c,d,e)};function Bd(a,b,c,d,e,f){Array.isArray(c)||(c&&(Md[0]=c.toString()),c=Md);for(var h=0;h<c.length;h++){var k=yd(b,c[h],d||a.handleEvent,e||!1,f||a.c||a);if(!k)break;a.a[k.key]=k}return a}g.nb=function(a,b,c,d){return Od(this,a,b,c,d)};g.Ob=function(a,b,c,d,e){return Od(this,a,b,c,d,e)};
function Od(a,b,c,d,e,f){if(Array.isArray(c))for(var h=0;h<c.length;h++)Od(a,b,c[h],d,e,f);else{b=zd(b,c,d||a.handleEvent,e,f||a.c||a);if(!b)return a;a.a[b.key]=b}return a}g.Qb=function(a,b,c,d){Bd(b,a,c,d,this.c||this);return this};g.Rb=function(a,b,c,d,e){Bd(b,a,c,d,e||this.c||this);return this};g.mb=function(){var a=0,b;for(b in this.a)Object.prototype.hasOwnProperty.call(this.a,b)&&a++;return a};
function Pd(a,b,c,d,e,f){if(Array.isArray(c))for(var h=0;h<c.length;h++)Pd(a,b,c[h],d,e,f);else d=d||a.handleEvent,e=w(e)?!!e.capture:!!e,f=f||a.c||a,d=Ad(d),e=!!e,b&&b[pd]?c=b.l(c,d,e,f):b?(b=Dd(b))?(c=b.a[c.toString()],b=-1,c&&(b=ud(c,d,e,f)),c=-1<b?c[b]:null):c=null:c=null,c&&(Hd(c),delete a.a[c.key])}g.lc=function(a,b,c,d,e){Pd(b,a,c,d,e||this.c||this,this);return this};function Qd(a){Sa(a.a,function(b,c){this.a.hasOwnProperty(c)&&Hd(b)},a);a.a={}}g.L=function(){Ld.H.L.call(this);Qd(this)};
g.handleEvent=function(){throw Error("EventHandler.handleEvent not implemented");};function Rd(a,b,c){a.timeOfStartCall=(new Date).getTime();var d=c||u,e=d.document,f=a.nonce||ra(d);f&&!a.nonce&&(a.nonce=f);if("help"==a.flow){var h=va("document.location.href",d);!a.helpCenterContext&&h&&(a.helpCenterContext=h.substring(0,1200));h=!0;if(b&&JSON&&JSON.stringify){var k=JSON.stringify(b);(h=1200>=k.length)&&(a.psdJson=k)}h||(b={invalidPsd:!0})}b=[a,b,c];d.GOOGLE_FEEDBACK_START_ARGUMENTS=b;c=a.serverUri||"//www.google.com/tools/feedback";if(h=d.GOOGLE_FEEDBACK_START)h.apply(d,b);else{d=
c+"/load.js?";for(var l in a)b=a[l],null==b||w(b)||(d+=encodeURIComponent(l)+"="+encodeURIComponent(b)+"&");a=Ac(e);a=U(a.a,"SCRIPT");f&&a.setAttribute("nonce",f);a.src=Ya(new A(Wa,d));(f=ra())&&a.setAttribute("nonce",f);e.body.appendChild(a)}}var Sd=["userfeedback","api","startFeedback"],X=u;Sd[0]in X||"undefined"==typeof X.execScript||X.execScript("var "+Sd[0]);for(var Y;Sd.length&&(Y=Sd.shift());)Sd.length||void 0===Rd?X[Y]&&X[Y]!==Object.prototype[Y]?X=X[Y]:X=X[Y]={}:X[Y]=Rd;function Z(){var a=V.call(this,["devsite-dialog"])||this;a.b=new Ld;a.c=!1;a.a=null;return a}ia(Z,V);
Z.prototype.connectedCallback=function(){if(!this.c){var a=this.querySelector(".google-feedback"),b=new Map([["data-b","bucket"],["data-context","context"],["data-p","product-id"]]),c=new Map([["data-label","Send Feedback Button"],["track-metadata-position","content"],["track-name","sendFeedbackLink"],["track-type","feedback"]]);if(a){b=p(b.entries());for(var d=b.next();!d.done;d=b.next()){var e=p(d.value);d=e.next().value;e=e.next().value;a.hasAttribute(d)&&(this.setAttribute(e,a.getAttribute(d)),
a.removeAttribute(d))}c=p(c.entries());for(b=c.next();!b.done;b=c.next())d=p(b.value),b=d.next().value,d=d.next().value,a.hasAttribute(b)?(this.setAttribute(b,a.getAttribute(b)),a.removeAttribute(b)):this.setAttribute(b,d);a.classList.remove("google-feedback")}this.hasAttribute("project-name")||(a=document.querySelector('meta[property="og:site_name"]'))&&this.setAttribute("project-name",a.getAttribute("content"));this.hasAttribute("project-icon")?this.setAttribute("project-icon",ed(this.getAttribute("project-icon")).href):
(a=document.querySelector('link[rel="apple-touch-icon"]'))&&this.setAttribute("project-icon",a.getAttribute("href"));c=this.getAttribute("project-name")||"";var f=this.getAttribute("project-icon");b=this.getAttribute("project-icon-name");d=this.getAttribute("project-feedback-url");e=this.getAttribute("project-support-url");a='<devsite-dialog class="devsite-feedback"><div class="devsite-dialog-contents"><h3>Kirim masukan tentang...</h3><div class="devsite-feedback-items"><a href="#" class="devsite-feedback-item" feedback-type="documentation" data-label="Docs Feedback Image" track-type="feedback" track-name="feedbackDocIcon"><div class="devsite-feedback-item-icon-container devsite-feedback-item-icon-color"><div class="devsite-feedback-item-icon material-icons" aria-hidden="true">description</div></div><div>Halaman ini</div><div class="devsite-feedback-item-type">Masukan dokumentasi';
b?f='<div class="devsite-feedback-item-icon material-icons" aria-hidden="true">'+gc(b)+"</div>":f?(K(f,Qb)||K(f,Rb)?f=Q(f):f instanceof B?f=Q(cb(f)):f instanceof A?f=Q(Ya(f).toString()):(f=String(f),f=tc.test(f)?f.replace(pc,qc):"about:invalid#zSoyz"),f='<img src="'+ic(f)+'">'):f="";a+="</div></a><a"+(d?' href="'+ic(nc(d))+'"':' href="#"')+' class="devsite-feedback-item" feedback-type="product" data-label="Product Feedback Image" track-type="feedback" track-name="feedbackProductIcon"><div class="devsite-feedback-item-icon-container '+
(b?"devsite-feedback-item-icon-color devsite-theme-primary":"devsite-feedback-item-icon-img")+'">'+f+"</div><div>"+gc(c)+'</div><div class="devsite-feedback-item-type">';a+="Masukan produk</div></a></div>";e&&(a+='<div class="devsite-feedback-support"><span class="devsite-feedback-support-icon material-icons" aria-hidden="true">help</span><span>',c='Perlu bantuan? Buka <a href="'+(ic(nc(e))+'">halaman dukungan</a> kami.'),a=a+c+"</span></div>");c=hc(a+'<div class="devsite-feedback-buttons"><button class="button-white" tabindex="1" data-label="Cancel Feedback Button" track-type="feedback" track-name="cancelFeedbackButton" feedback-cancel>Tutup</button></div></div></devsite-dialog>');
a=Ac();a=U(a.a,"DIV");if(w(c))if(c instanceof J){if(c.K!==Pb)throw Error("Sanitized content was not of kind HTML.");c=kb(c.toString(),c.J||null)}else c=fb("zSoyz");else c=fb(String(c));nb(a,c);1==a.childNodes.length&&(c=a.firstChild,1==c.nodeType&&(a=c));this.a=a;this.c=!0}Td(this)};Z.prototype.disconnectedCallback=function(){Qd(this.b)};
function Td(a){Nd(a.b,a,"click",function(b){b.B();b.F();a.a&&(document.body.appendChild(a.a),a.a.setAttribute("open",""),b={action:"click",category:a.getAttribute("data-category")||"Site-Wide Custom Events",label:a.getAttribute("data-label")},Ud(a,b))});a.a&&(Array.from(a.a.querySelectorAll("[feedback-type]")).forEach(function(b){Nd(a.b,b,"click",function(c){c.B();c.F();c=c.w;var d=c.getAttribute("feedback-type");d={context:a.getAttribute("context"),type:d};var e={productId:a.getAttribute("product-id"),
locale:DevsiteApp.getLocale(),bucket:a.getAttribute("bucket"),productVersion:a.getAttribute("version"),callback:a.i.bind(a),onLoadCallback:a.f.bind(a)};c={action:"click",label:c.getAttribute("data-label"),category:c.getAttribute("data-category")||"Site-Wide Custom Events"};Ud(a,c);Rd(e,d)})}),Nd(a.b,a.a.querySelector("button[feedback-cancel]"),"click",function(){a.f();var b=a.a.querySelector("button[feedback-cancel]");b={action:"click",label:b.getAttribute("data-label"),category:b.getAttribute("data-category")||
"Site-Wide Custom Events"};Ud(a,b)}),Nd(a.b,a.a,"devsite-dialog-hide",function(){Oc(a.a)}))}Z.prototype.f=function(){this.a.removeAttribute("open");Oc(this.a)};Z.prototype.i=function(){Array.from(document.querySelectorAll('script[src*="www.google.com/tools/feedback/"]')).forEach(function(a){return Oc(a)})};function Ud(a,b){a.dispatchEvent(new CustomEvent("devsite-analytics-observation",{detail:b,bubbles:!0}))}Z.prototype.disconnectedCallback=Z.prototype.disconnectedCallback;
Z.prototype.connectedCallback=Z.prototype.connectedCallback;try{window.customElements.define("devsite-feedback",Z)}catch(a){console.warn("devsite.app.customElement.DevsiteFeedback",a)};}).call(this);
