(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var h;function aa(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}function n(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):{next:aa(a)}}var ba="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},p;
if("function"==typeof Object.setPrototypeOf)p=Object.setPrototypeOf;else{var ca;a:{var ha={N:!0},ia={};try{ia.__proto__=ha;ca=ia.N;break a}catch(a){}ca=!1}p=ca?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var ja=p;
function ka(a,b){a.prototype=ba(b.prototype);a.prototype.constructor=a;if(ja)ja(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.C=b.prototype}function la(a){a=["object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global,a];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}
var q=la(this),ma="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};function r(a,b){if(b){var c=q;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&ma(c,a,{configurable:!0,writable:!0,value:b})}}
r("Promise",function(a){function b(f){this.b=0;this.g=void 0;this.a=[];var k=this.c();try{f(k.resolve,k.reject)}catch(l){k.reject(l)}}function c(){this.a=null}function d(f){return f instanceof b?f:new b(function(k){k(f)})}if(a)return a;c.prototype.b=function(f){if(null==this.a){this.a=[];var k=this;this.c(function(){k.g()})}this.a.push(f)};var e=q.setTimeout;c.prototype.c=function(f){e(f,0)};c.prototype.g=function(){for(;this.a&&this.a.length;){var f=this.a;this.a=[];for(var k=0;k<f.length;++k){var l=
f[k];f[k]=null;try{l()}catch(m){this.f(m)}}}this.a=null};c.prototype.f=function(f){this.c(function(){throw f;})};b.prototype.c=function(){function f(m){return function(t){l||(l=!0,m.call(k,t))}}var k=this,l=!1;return{resolve:f(this.B),reject:f(this.f)}};b.prototype.B=function(f){if(f===this)this.f(new TypeError("A Promise cannot resolve to itself"));else if(f instanceof b)this.H(f);else{a:switch(typeof f){case "object":var k=null!=f;break a;case "function":k=!0;break a;default:k=!1}k?this.o(f):this.h(f)}};
b.prototype.o=function(f){var k=void 0;try{k=f.then}catch(l){this.f(l);return}"function"==typeof k?this.I(k,f):this.h(f)};b.prototype.f=function(f){this.i(2,f)};b.prototype.h=function(f){this.i(1,f)};b.prototype.i=function(f,k){if(0!=this.b)throw Error("Cannot settle("+f+", "+k+"): Promise already settled in state"+this.b);this.b=f;this.g=k;this.j()};b.prototype.j=function(){if(null!=this.a){for(var f=0;f<this.a.length;++f)g.b(this.a[f]);this.a=null}};var g=new c;b.prototype.H=function(f){var k=this.c();
f.w(k.resolve,k.reject)};b.prototype.I=function(f,k){var l=this.c();try{f.call(k,l.resolve,l.reject)}catch(m){l.reject(m)}};b.prototype.then=function(f,k){function l(w,C){return"function"==typeof w?function(da){try{m(w(da))}catch(ea){t(ea)}}:C}var m,t,fa=new b(function(w,C){m=w;t=C});this.w(l(f,m),l(k,t));return fa};b.prototype.catch=function(f){return this.then(void 0,f)};b.prototype.w=function(f,k){function l(){switch(m.b){case 1:f(m.g);break;case 2:k(m.g);break;default:throw Error("Unexpected state: "+
m.b);}}var m=this;null==this.a?g.b(l):this.a.push(l)};b.resolve=d;b.reject=function(f){return new b(function(k,l){l(f)})};b.race=function(f){return new b(function(k,l){for(var m=n(f),t=m.next();!t.done;t=m.next())d(t.value).w(k,l)})};b.all=function(f){var k=n(f),l=k.next();return l.done?d([]):new b(function(m,t){function fa(da){return function(ea){w[da]=ea;C--;0==C&&m(w)}}var w=[],C=0;do w.push(void 0),C++,d(l.value).w(fa(w.length-1),t),l=k.next();while(!l.done)})};return b});
function na(){na=function(){};q.Symbol||(q.Symbol=oa)}function pa(a,b){this.a=a;ma(this,"description",{configurable:!0,writable:!0,value:b})}pa.prototype.toString=function(){return this.a};var oa=function(){function a(c){if(this instanceof a)throw new TypeError("Symbol is not a constructor");return new pa("jscomp_symbol_"+(c||"")+"_"+b++,c)}var b=0;return a}();
function qa(){na();var a=q.Symbol.iterator;a||(a=q.Symbol.iterator=q.Symbol("Symbol.iterator"));"function"!=typeof Array.prototype[a]&&ma(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return ra(aa(this))}});qa=function(){}}function ra(a){qa();a={next:a};a[q.Symbol.iterator]=function(){return this};return a}function sa(a){if(!(a instanceof Object))throw new TypeError("Iterator result "+a+" is not an object");}
function ta(){this.h=!1;this.f=null;this.j=void 0;this.a=1;this.c=this.g=0;this.i=this.b=null}function ua(a){if(a.h)throw new TypeError("Generator is already running");a.h=!0}h=ta.prototype;h.D=function(a){this.j=a};function va(a,b){a.b={K:b,M:!0};a.a=a.g||a.c}h.return=function(a){this.b={return:a};this.a=this.c};h.ua=function(a){this.b={u:a};this.a=this.c};h.Na=function(a,b){a=n(a);var c=a.next();sa(c);if(c.done)this.j=c.value,this.a=b;else return this.f=a,a=c.value,this.a=b,{value:a}};
h.u=function(a){this.a=a};h.Da=function(a,b){this.g=a;void 0!=b&&(this.c=b)};h.Ea=function(a){this.g=0;this.c=a||0};h.wa=function(a,b){this.a=a;this.g=b||0};h.R=function(a){this.g=a||0;a=this.b.K;this.b=null;return a};h.S=function(a,b,c){c?this.i[c]=this.b:this.i=[this.b];this.g=a||0;this.c=b||0};h.va=function(a,b){b=this.i.splice(b||0)[0];(b=this.b=this.b||b)?b.M?this.a=this.g||this.c:void 0!=b.u&&this.c<b.u?(this.a=b.u,this.b=null):this.a=this.c:this.a=a};h.V=function(a){return new wa(a)};
function wa(a){this.b=a;this.a=[];for(var b in a)this.a.push(b);this.a.reverse()}wa.prototype.c=function(){for(;0<this.a.length;){var a=this.a.pop();if(a in this.b)return a}return null};function xa(a){this.a=new ta;this.b=a}function ya(a,b){ua(a.a);var c=a.a.f;if(c)return za(a,"return"in c?c["return"]:function(d){return{value:d,done:!0}},b,a.a.return);a.a.return(b);return u(a)}
function za(a,b,c,d){try{var e=b.call(a.a.f,c);sa(e);if(!e.done)return a.a.h=!1,e;var g=e.value}catch(f){return a.a.f=null,va(a.a,f),u(a)}a.a.f=null;d.call(a.a,g);return u(a)}function u(a){for(;a.a.a;)try{var b=a.b(a.a);if(b)return a.a.h=!1,{value:b.value,done:!1}}catch(c){a.a.j=void 0,va(a.a,c)}a.a.h=!1;if(a.a.b){b=a.a.b;a.a.b=null;if(b.M)throw b.K;return{value:b.return,done:!0}}return{value:void 0,done:!0}}
function Aa(a){this.next=function(b){ua(a.a);a.a.f?b=za(a,a.a.f.next,b,a.a.D):(a.a.D(b),b=u(a));return b};this.throw=function(b){ua(a.a);a.a.f?b=za(a,a.a.f["throw"],b,a.a.D):(va(a.a,b),b=u(a));return b};this.return=function(b){return ya(a,b)};qa();this[Symbol.iterator]=function(){return this}}function Ba(a){function b(d){return a.next(d)}function c(d){return a.throw(d)}new Promise(function(d,e){function g(f){f.done?d(f.value):Promise.resolve(f.value).then(b,c).then(g,e)}g(a.next())})}
r("Array.prototype.find",function(a){return a?a:function(b,c){a:{var d=this;d instanceof String&&(d=String(d));for(var e=d.length,g=0;g<e;g++){var f=d[g];if(b.call(c,f,g,d)){b=f;break a}}b=void 0}return b}});r("Object.is",function(a){return a?a:function(b,c){return b===c?0!==b||1/b===1/c:b!==b&&c!==c}});
r("Array.prototype.includes",function(a){return a?a:function(b,c){var d=this;d instanceof String&&(d=String(d));var e=d.length;c=c||0;for(0>c&&(c=Math.max(c+e,0));c<e;c++){var g=d[c];if(g===b||Object.is(g,b))return!0}return!1}});
var Ca=function(){function a(){function c(){}new c;Reflect.construct(c,[],function(){});return new c instanceof c}if("undefined"!=typeof Reflect&&Reflect.construct){if(a())return Reflect.construct;var b=Reflect.construct;return function(c,d,e){c=b(c,d);e&&Reflect.setPrototypeOf(c,e.prototype);return c}}return function(c,d,e){void 0===e&&(e=c);e=ba(e.prototype||Object.prototype);return Function.prototype.apply.call(c,e,d)||e}}();r("Reflect.construct",function(){return Ca});
r("Object.setPrototypeOf",function(a){return a||ja});r("Array.from",function(a){return a?a:function(b,c,d){c=null!=c?c:function(k){return k};var e=[],g="undefined"!=typeof Symbol&&Symbol.iterator&&b[Symbol.iterator];if("function"==typeof g){b=g.call(b);for(var f=0;!(g=b.next()).done;)e.push(c.call(d,g.value,f++))}else for(g=b.length,f=0;f<g;f++)e.push(c.call(d,b[f],f));return e}});var v=this||self;function Da(){}
function Ea(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b}function Fa(a){var b=Ea(a);return"array"==b||"object"==b&&"number"==typeof a.length}function x(a){var b=typeof a;return"object"==b&&null!=a||"function"==b}function Ga(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var d=c.slice();d.push.apply(d,arguments);return a.apply(this,d)}}var Ha=Date.now||function(){return+new Date};
function Ia(a,b){function c(){}c.prototype=b.prototype;a.C=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.P=function(d,e,g){for(var f=Array(arguments.length-2),k=2;k<arguments.length;k++)f[k-2]=arguments[k];return b.prototype[e].apply(d,f)}};var y=Array.prototype.indexOf?function(a,b){return Array.prototype.indexOf.call(a,b,void 0)}:function(a,b){if("string"===typeof a)return"string"!==typeof b||1!=b.length?-1:a.indexOf(b,0);for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},Ja=Array.prototype.forEach?function(a,b,c){Array.prototype.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e="string"===typeof a?a.split(""):a,g=0;g<d;g++)g in e&&b.call(c,e[g],g,a)};
function Ka(a){return Array.prototype.concat.apply([],arguments)}function La(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]};var Ma=String.prototype.trim?function(a){return a.trim()}:function(a){return/^[\s\xa0]*([\s\S]*?)[\s\xa0]*$/.exec(a)[1]};function z(a,b){return-1!=a.indexOf(b)}function Na(a,b){return a<b?-1:a>b?1:0};var A;a:{var Oa=v.navigator;if(Oa){var Pa=Oa.userAgent;if(Pa){A=Pa;break a}}A=""};function Qa(a,b,c){for(var d in a)b.call(c,a[d],d,a)}function Ra(a,b){for(var c in a)if(b.call(void 0,a[c],c,a))return!0;return!1};function Sa(a){Sa[" "](a);return a}Sa[" "]=Da;function Ta(a){var b=Ua;return Object.prototype.hasOwnProperty.call(b,"9")?b["9"]:b["9"]=a("9")};var Va=z(A,"Opera"),B=z(A,"Trident")||z(A,"MSIE"),Wa=z(A,"Edge"),Xa=z(A,"Gecko")&&!(z(A.toLowerCase(),"webkit")&&!z(A,"Edge"))&&!(z(A,"Trident")||z(A,"MSIE"))&&!z(A,"Edge"),D=z(A.toLowerCase(),"webkit")&&!z(A,"Edge"),Ya=z(A,"Macintosh");function Za(){var a=v.document;return a?a.documentMode:void 0}var $a;
a:{var ab="",bb=function(){var a=A;if(Xa)return/rv:([^\);]+)(\)|;)/.exec(a);if(Wa)return/Edge\/([\d\.]+)/.exec(a);if(B)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(D)return/WebKit\/(\S+)/.exec(a);if(Va)return/(?:Version)[ \/]?(\S+)/.exec(a)}();bb&&(ab=bb?bb[1]:"");if(B){var cb=Za();if(null!=cb&&cb>parseFloat(ab)){$a=String(cb);break a}}$a=ab}var db=$a,Ua={};
function eb(){return Ta(function(){for(var a=0,b=Ma(String(db)).split("."),c=Ma("9").split("."),d=Math.max(b.length,c.length),e=0;0==a&&e<d;e++){var g=b[e]||"",f=c[e]||"";do{g=/(\d*)(\D*)(.*)/.exec(g)||["","","",""];f=/(\d*)(\D*)(.*)/.exec(f)||["","","",""];if(0==g[0].length&&0==f[0].length)break;a=Na(0==g[1].length?0:parseInt(g[1],10),0==f[1].length?0:parseInt(f[1],10))||Na(0==g[2].length,0==f[2].length)||Na(g[2],f[2]);g=g[3];f=f[3]}while(0==a)}return 0<=a})}var fb;fb=v.document&&B?Za():void 0;function gb(a,b){var c=[];hb(a,b,c,!1);return c}function hb(a,b,c,d){if(null!=a)for(a=a.firstChild;a;){if(b(a)&&(c.push(a),d)||hb(a,b,c,d))return!0;a=a.nextSibling}return!1}function ib(a){return B&&!eb()?(a=a.getAttributeNode("tabindex"),null!=a&&a.specified):a.hasAttribute("tabindex")}function jb(a){a=a.tabIndex;return"number"===typeof a&&0<=a&&32768>a}
function kb(a){return lb(a,function(b){var c;if(c="string"===typeof b.className)c=0<=y(b.className.split(/\s+/),"devsite-dialog-close");return c},!0,5)}function lb(a,b,c,d){a&&!c&&(a=a.parentNode);for(c=0;a&&(null==d||c<=d);){if(b(a))return a;a=a.parentNode;c++}return null};var mb="StopIteration"in v?v.StopIteration:{message:"StopIteration",stack:""};function nb(){}nb.prototype.next=function(){throw mb;};nb.prototype.a=function(){return this};function E(a,b){this.b={};this.a=[];this.f=this.c=0;var c=arguments.length;if(1<c){if(c%2)throw Error("Uneven number of arguments");for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else if(a)if(a instanceof E)for(c=a.m(),d=0;d<c.length;d++)this.set(c[d],a.get(c[d]));else for(d in a)this.set(d,a[d])}h=E.prototype;h.l=function(){F(this);for(var a=[],b=0;b<this.a.length;b++)a.push(this.b[this.a[b]]);return a};h.m=function(){F(this);return this.a.concat()};
h.qa=function(a){for(var b=0;b<this.a.length;b++){var c=this.a[b];if(G(this.b,c)&&this.b[c]==a)return!0}return!1};h.T=function(a,b){if(this===a)return!0;if(this.c!=a.c)return!1;b=b||ob;F(this);for(var c,d=0;c=this.a[d];d++)if(!b(this.get(c),a.get(c)))return!1;return!0};function ob(a,b){return a===b}h.ra=function(){return 0==this.c};h.pa=function(){this.b={};this.f=this.c=this.a.length=0};
function F(a){if(a.c!=a.a.length){for(var b=0,c=0;b<a.a.length;){var d=a.a[b];G(a.b,d)&&(a.a[c++]=d);b++}a.a.length=c}if(a.c!=a.a.length){var e={};for(c=b=0;b<a.a.length;)d=a.a[b],G(e,d)||(a.a[c++]=d,e[d]=1),b++;a.a.length=c}}h.get=function(a,b){return G(this.b,a)?this.b[a]:b};h.set=function(a,b){G(this.b,a)||(this.c++,this.a.push(a),this.f++);this.b[a]=b};h.forEach=function(a,b){for(var c=this.m(),d=0;d<c.length;d++){var e=c[d],g=this.get(e);a.call(b,g,e,this)}};
h.Ja=function(){for(var a=new E,b=0;b<this.a.length;b++){var c=this.a[b];a.set(this.b[c],c)}return a};h.Ia=function(){F(this);for(var a={},b=0;b<this.a.length;b++){var c=this.a[b];a[c]=this.b[c]}return a};h.Y=function(){return pb(this,!0)};h.aa=function(){return pb(this,!1)};function pb(a,b){F(a);var c=0,d=a.f,e=new nb;e.next=function(){if(d!=a.f)throw Error("The map has changed since the iterator was created");if(c>=a.a.length)throw mb;var g=a.a[c++];return b?g:a.b[g]};return e}
function G(a,b){return Object.prototype.hasOwnProperty.call(a,b)};function qb(a){if(a.l&&"function"==typeof a.l)return a.l();if("string"===typeof a)return a.split("");if(Fa(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}b=[];c=0;for(d in a)b[c++]=a[d];return b}
function rb(a,b,c){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,c);else if(Fa(a)||"string"===typeof a)Ja(a,b,c);else{if(a.m&&"function"==typeof a.m)var d=a.m();else if(a.l&&"function"==typeof a.l)d=void 0;else if(Fa(a)||"string"===typeof a){d=[];for(var e=a.length,g=0;g<e;g++)d.push(g)}else for(g in d=[],e=0,a)d[e++]=g;e=qb(a);g=e.length;for(var f=0;f<g;f++)b.call(c,e[f],d&&d[f],a)}};var sb=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^/?#]*)@)?([^/#?]*?)(?::([0-9]+))?(?=[/\\#?]|$))?([^?#]+)?(?:\?([^#]*))?(?:#([\s\S]*))?$/;function tb(a,b){if(a){a=a.split("&");for(var c=0;c<a.length;c++){var d=a[c].indexOf("="),e=null;if(0<=d){var g=a[c].substring(0,d);e=a[c].substring(d+1)}else g=a[c];b(g,e?decodeURIComponent(e.replace(/\+/g," ")):"")}}};function H(a){this.b=this.j=this.h="";this.f=null;this.i=this.c="";this.g=this.o=!1;if(a instanceof H){this.g=a.g;ub(this,a.h);var b=a.j;I(this);this.j=b;b=a.b;I(this);this.b=b;vb(this,a.f);b=a.c;I(this);this.c=b;J(this,wb(a.a));a=a.i;I(this);this.i=a}else a&&(b=String(a).match(sb))?(this.g=!1,ub(this,b[1]||"",!0),a=b[2]||"",I(this),this.j=K(a),a=b[3]||"",I(this),this.b=K(a,!0),vb(this,b[4]),a=b[5]||"",I(this),this.c=K(a,!0),J(this,b[6]||"",!0),a=b[7]||"",I(this),this.i=K(a)):(this.g=!1,this.a=new L(null,
this.g))}h=H.prototype;h.toString=function(){var a=[],b=this.h;b&&a.push(M(b,xb,!0),":");var c=this.b;if(c||"file"==b)a.push("//"),(b=this.j)&&a.push(M(b,xb,!0),"@"),a.push(encodeURIComponent(String(c)).replace(/%25([0-9a-fA-F]{2})/g,"%$1")),c=this.f,null!=c&&a.push(":",String(c));if(c=this.c)this.b&&"/"!=c.charAt(0)&&a.push("/"),a.push(M(c,"/"==c.charAt(0)?yb:zb,!0));(c=this.a.toString())&&a.push("?",c);(c=this.i)&&a.push("#",M(c,Ab));return a.join("")};
h.resolve=function(a){var b=new H(this),c=!!a.h;c?ub(b,a.h):c=!!a.j;if(c){var d=a.j;I(b);b.j=d}else c=!!a.b;c?(d=a.b,I(b),b.b=d):c=null!=a.f;d=a.c;if(c)vb(b,a.f);else if(c=!!a.c){if("/"!=d.charAt(0))if(this.b&&!this.c)d="/"+d;else{var e=b.c.lastIndexOf("/");-1!=e&&(d=b.c.substr(0,e+1)+d)}e=d;if(".."==e||"."==e)d="";else if(z(e,"./")||z(e,"/.")){d=0==e.lastIndexOf("/",0);e=e.split("/");for(var g=[],f=0;f<e.length;){var k=e[f++];"."==k?d&&f==e.length&&g.push(""):".."==k?((1<g.length||1==g.length&&""!=
g[0])&&g.pop(),d&&f==e.length&&g.push("")):(g.push(k),d=!0)}d=g.join("/")}else d=e}c?(I(b),b.c=d):c=""!==a.a.toString();c?J(b,wb(a.a)):c=!!a.i;c&&(a=a.i,I(b),b.i=a);return b};function ub(a,b,c){I(a);a.h=c?K(b,!0):b;a.h&&(a.h=a.h.replace(/:$/,""))}function vb(a,b){I(a);if(b){b=Number(b);if(isNaN(b)||0>b)throw Error("Bad port number "+b);a.f=b}else a.f=null}function J(a,b,c){I(a);b instanceof L?(a.a=b,Bb(a.a,a.g)):(c||(b=M(b,Cb)),a.a=new L(b,a.g));return a}h.Ga=function(a,b){return J(this,a,b)};
h.W=function(){return K(this.a.toString())};h.ga=function(){return this.a.toString()};h.Fa=function(a,b){I(this);Array.isArray(b)||(b=[String(b)]);Db(this.a,a,b);return this};h.$=function(a){return this.a.l(a)};h.sa=function(a){return(!this.b&&!a.b||this.b==a.b)&&(null==this.f&&null==a.f||this.f==a.f)};h.Ba=function(){I(this);var a=Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^Ha()).toString(36);I(this);this.a.set("zx",a);return this};
h.ha=function(a){I(this);N(this.a,a);return this};h.Ha=function(a){this.o=a;return this};h.ta=function(){return this.o};function I(a){if(a.o)throw Error("Tried to modify a read-only Uri");}h.ia=function(a){this.g=a;this.a&&Bb(this.a,a);return this};function K(a,b){return a?b?decodeURI(a.replace(/%25/g,"%2525")):decodeURIComponent(a):""}function M(a,b,c){return"string"===typeof a?(a=encodeURI(a).replace(b,Eb),c&&(a=a.replace(/%25([0-9a-fA-F]{2})/g,"%$1")),a):null}
function Eb(a){a=a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)}var xb=/[#\/\?@]/g,zb=/[#\?:]/g,yb=/[#\?]/g,Cb=/[#\?@]/g,Ab=/#/g;function L(a,b){this.b=this.a=null;this.c=a||null;this.f=!!b}function O(a){a.a||(a.a=new E,a.b=0,a.c&&tb(a.c,function(b,c){a.add(decodeURIComponent(b.replace(/\+/g," ")),c)}))}h=L.prototype;h.ea=function(){O(this);return this.b};h.add=function(a,b){O(this);this.c=null;a=P(this,a);var c=this.a.get(a);c||this.a.set(a,c=[]);c.push(b);this.b+=1;return this};
function N(a,b){O(a);b=P(a,b);G(a.a.b,b)&&(a.c=null,a.b-=a.a.get(b).length,a=a.a,G(a.b,b)&&(delete a.b[b],a.c--,a.f++,a.a.length>2*a.c&&F(a)))}h.ba=function(){this.a=this.c=null;this.b=0};h.fa=function(){O(this);return 0==this.b};function Fb(a,b){O(a);b=P(a,b);return G(a.a.b,b)}h.ca=function(a){var b=this.l();return 0<=y(b,a)};h.forEach=function(a,b){O(this);this.a.forEach(function(c,d){Ja(c,function(e){a.call(b,e,d,this)},this)},this)};
h.m=function(){O(this);for(var a=this.a.l(),b=this.a.m(),c=[],d=0;d<b.length;d++)for(var e=a[d],g=0;g<e.length;g++)c.push(b[d]);return c};h.l=function(a){O(this);var b=[];if("string"===typeof a)Fb(this,a)&&(b=Ka(b,this.a.get(P(this,a))));else{a=this.a.l();for(var c=0;c<a.length;c++)b=Ka(b,a[c])}return b};h.set=function(a,b){O(this);this.c=null;a=P(this,a);Fb(this,a)&&(this.b-=this.a.get(a).length);this.a.set(a,[b]);this.b+=1;return this};
h.get=function(a,b){if(!a)return b;a=this.l(a);return 0<a.length?String(a[0]):b};function Db(a,b,c){N(a,b);0<c.length&&(a.c=null,a.a.set(P(a,b),La(c)),a.b+=c.length)}h.toString=function(){if(this.c)return this.c;if(!this.a)return"";for(var a=[],b=this.a.m(),c=0;c<b.length;c++){var d=b[c],e=encodeURIComponent(String(d));d=this.l(d);for(var g=0;g<d.length;g++){var f=e;""!==d[g]&&(f+="="+encodeURIComponent(String(d[g])));a.push(f)}}return this.c=a.join("&")};
h.U=function(a){O(this);this.a.forEach(function(b,c){0<=y(a,c)||N(this,c)},this);return this};function wb(a){var b=new L;b.c=a.c;a.a&&(b.a=new E(a.a),b.b=a.b);return b}function P(a,b){b=String(b);a.f&&(b=b.toLowerCase());return b}function Bb(a,b){b&&!a.f&&(O(a),a.c=null,a.a.forEach(function(c,d){var e=d.toLowerCase();d!=e&&(N(this,d),Db(this,e,c))},a));a.f=b}h.da=function(a){for(var b=0;b<arguments.length;b++)rb(arguments[b],function(c,d){this.add(d,c)},this)};var Gb=!/^\s*class\s*\{\s*\}\s*$/.test(function(){}.toString());/*

 Copyright (c) 2016 The Polymer Project Authors. All rights reserved.
 This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
 The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
 The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
 Code distributed by Google as part of the polymer project is also
 subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
(function(){if(Gb&&!HTMLElement.es5Shimmed&&void 0!==window.Reflect&&void 0!==window.customElements&&!window.customElements.polyfillWrapFlushCallback){var a=HTMLElement;window.HTMLElement=function(){return Reflect.construct(a,[],this.constructor)};HTMLElement.prototype=a.prototype;HTMLElement.prototype.constructor=HTMLElement;HTMLElement.es5Shimmed=!0;Object.setPrototypeOf(HTMLElement,a)}})();function Q(a){var b=HTMLElement.call(this)||this;a&&("string"===typeof a&&(a=[a]),document.body.dispatchEvent(new CustomEvent("devsite-load-custom-elements",{bubbles:!0,detail:a})));return b}ka(Q,HTMLElement);Q.prototype.Ma=function(){console.warn(this.tagName,"has not implemented update")};Q.prototype.o=function(a){a=void 0===a?"":a;return document.createRange().createContextualFragment(a||"")};
Q.prototype.La=function(a,b,c){a&&b?a.parentNode.replaceChild(document.importNode(b,!0),a):!b&&a?a.parentNode.removeChild(a):!a&&b&&(c?(a=document.importNode(b,!0),c.parentElement.insertBefore(a,c.nextSibling)):this.appendChild(document.importNode(b,!0)))};var Hb=!B||9<=Number(fb),Ib=!B||9<=Number(fb),Jb=B&&!eb(),Kb=function(){if(!v.addEventListener||!Object.defineProperty)return!1;var a=!1,b=Object.defineProperty({},"passive",{get:function(){a=!0}});try{v.addEventListener("test",Da,b),v.removeEventListener("test",Da,b)}catch(c){}return a}();function R(){this.s=this.s;this.b=this.b}h=R.prototype;h.s=!1;h.O=function(){return this.s};h.X=R.prototype.O;h.J=function(){this.s||(this.s=!0,this.G())};h.Ca=function(a){a=Ga(Lb,a);this.s?a():(this.b||(this.b=[]),this.b.push(a))};h.G=function(){if(this.b)for(;this.b.length;)this.b.shift()()};function Lb(a){a&&"function"==typeof a.J&&a.J()};function S(a,b){this.type=a;this.b=this.target=b;this.o=this.c=!1}S.prototype.f=function(){this.c=!0};S.prototype.A=function(){this.o=!0};function T(a,b){S.call(this,a?a.type:"");this.relatedTarget=this.b=this.target=null;this.button=this.screenY=this.screenX=this.clientY=this.clientX=this.i=this.h=0;this.key="";this.g=this.L=0;this.metaKey=this.shiftKey=this.altKey=this.ctrlKey=!1;this.j=null;this.B=!1;this.pointerId=0;this.pointerType="";this.a=null;if(a){var c=this.type=a.type,d=a.changedTouches&&a.changedTouches.length?a.changedTouches[0]:null;this.target=a.target||a.srcElement;this.b=b;if(b=a.relatedTarget){if(Xa){a:{try{Sa(b.nodeName);
var e=!0;break a}catch(g){}e=!1}e||(b=null)}}else"mouseover"==c?b=a.fromElement:"mouseout"==c&&(b=a.toElement);this.relatedTarget=b;d?(this.clientX=void 0!==d.clientX?d.clientX:d.pageX,this.clientY=void 0!==d.clientY?d.clientY:d.pageY,this.screenX=d.screenX||0,this.screenY=d.screenY||0):(this.h=D||void 0!==a.offsetX?a.offsetX:a.layerX,this.i=D||void 0!==a.offsetY?a.offsetY:a.layerY,this.clientX=void 0!==a.clientX?a.clientX:a.pageX,this.clientY=void 0!==a.clientY?a.clientY:a.pageY,this.screenX=a.screenX||
0,this.screenY=a.screenY||0);this.button=a.button;this.L=a.keyCode||0;this.key=a.key||"";this.g=a.charCode||("keypress"==c?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.B=Ya?a.metaKey:a.ctrlKey;this.pointerId=a.pointerId||0;this.pointerType="string"===typeof a.pointerType?a.pointerType:Mb[a.pointerType]||"";this.j=a.state;this.a=a;a.defaultPrevented&&this.A()}}Ia(T,S);var Nb=[1,4,2],Mb={2:"touch",3:"pen",4:"mouse"};
T.prototype.I=function(){return(Hb?0==this.a.button:"click"==this.type?!0:!!(this.a.button&Nb[0]))&&!(D&&Ya&&this.ctrlKey)};T.prototype.f=function(){T.C.f.call(this);this.a.stopPropagation?this.a.stopPropagation():this.a.cancelBubble=!0};T.prototype.A=function(){T.C.A.call(this);var a=this.a;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,Jb)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};T.prototype.H=function(){return this.a};var U="closure_listenable_"+(1E6*Math.random()|0),Ob=0;function Pb(a,b,c,d,e){this.listener=a;this.a=null;this.src=b;this.type=c;this.capture=!!d;this.b=e;this.key=++Ob;this.v=this.F=!1}function V(a){a.v=!0;a.listener=null;a.a=null;a.src=null;a.b=null};function Qb(a){this.src=a;this.a={};this.b=0}h=Qb.prototype;h.la=function(){var a=0,b;for(b in this.a)a+=this.a[b].length;return a};h.add=function(a,b,c,d,e){var g=a.toString();a=this.a[g];a||(a=this.a[g]=[],this.b++);var f=Rb(a,b,d,e);-1<f?(b=a[f],c||(b.F=!1)):(b=new Pb(b,this.src,g,!!d,e),b.F=c,a.push(b));return b};
h.na=function(a,b,c,d){a=a.toString();if(!(a in this.a))return!1;var e=this.a[a];b=Rb(e,b,c,d);return-1<b?(V(e[b]),Array.prototype.splice.call(e,b,1),0==e.length&&(delete this.a[a],this.b--),!0):!1};h.oa=function(a){a=a&&a.toString();var b=0,c;for(c in this.a)if(!a||c==a){for(var d=this.a[c],e=0;e<d.length;e++)++b,V(d[e]);delete this.a[c];this.b--}return b};h.Z=function(a,b){a=this.a[a.toString()];var c=[];if(a)for(var d=0;d<a.length;++d){var e=a[d];e.capture==b&&c.push(e)}return c};
h.ma=function(a,b){var c=void 0!==a,d=c?a.toString():"",e=void 0!==b;return Ra(this.a,function(g){for(var f=0;f<g.length;++f)if(!(c&&g[f].type!=d||e&&g[f].capture!=b))return!0;return!1})};function Rb(a,b,c,d){for(var e=0;e<a.length;++e){var g=a[e];if(!g.v&&g.listener==b&&g.capture==!!c&&g.b==d)return e}return-1};var Sb="closure_lm_"+(1E6*Math.random()|0),Tb={},Ub=0;function Vb(a,b,c,d,e){if(d&&d.once)return Wb(a,b,c,d,e);if(Array.isArray(b)){for(var g=0;g<b.length;g++)Vb(a,b[g],c,d,e);return null}c=Xb(c);return a&&a[U]?W(a,b,c,x(d)?!!d.capture:!!d,e):Yb(a,b,c,!1,d,e)}
function Yb(a,b,c,d,e,g){if(!b)throw Error("Invalid event type");var f=x(e)?!!e.capture:!!e,k=X(a);k||(a[Sb]=k=new Qb(a));c=k.add(b,c,d,f,g);if(c.a)return c;d=Zb();c.a=d;d.src=a;d.listener=c;if(a.addEventListener)Kb||(e=f),void 0===e&&(e=!1),a.addEventListener(b.toString(),d,e);else if(a.attachEvent)a.attachEvent($b(b.toString()),d);else if(a.addListener&&a.removeListener)a.addListener(d);else throw Error("addEventListener and attachEvent are unavailable.");Ub++;return c}
function Zb(){var a=ac,b=Ib?function(c){return a.call(b.src,b.listener,c)}:function(c){c=a.call(b.src,b.listener,c);if(!c)return c};return b}function Wb(a,b,c,d,e){if(Array.isArray(b)){for(var g=0;g<b.length;g++)Wb(a,b[g],c,d,e);return null}c=Xb(c);return a&&a[U]?a.H(b,c,x(d)?!!d.capture:!!d,e):Yb(a,b,c,!0,d,e)}
function bc(a){if("number"!==typeof a&&a&&!a.v){var b=a.src;if(b&&b[U])b.a(a);else{var c=a.type,d=a.a;b.removeEventListener?b.removeEventListener(c,d,a.capture):b.detachEvent?b.detachEvent($b(c),d):b.addListener&&b.removeListener&&b.removeListener(d);Ub--;if(c=X(b)){d=a.type;if(d in c.a){var e=c.a[d],g=y(e,a),f;(f=0<=g)&&Array.prototype.splice.call(e,g,1);f&&(V(a),0==c.a[d].length&&(delete c.a[d],c.b--))}0==c.b&&(c.src=null,b[Sb]=null)}else V(a)}}}
function $b(a){return a in Tb?Tb[a]:Tb[a]="on"+a}function cc(a,b,c,d){var e=!0;if(a=X(a))if(b=a.a[b.toString()])for(b=b.concat(),a=0;a<b.length;a++){var g=b[a];g&&g.capture==c&&!g.v&&(g=dc(g,d),e=e&&!1!==g)}return e}function dc(a,b){var c=a.listener,d=a.b||a.src;a.F&&bc(a);return c.call(d,b)}
function ac(a,b){if(a.v)return!0;if(!Ib){if(!b)a:{b=["window","event"];for(var c=v,d=0;d<b.length;d++)if(c=c[b[d]],null==c){b=null;break a}b=c}d=b;b=new T(d,this);c=!0;if(!(0>d.keyCode||void 0!=d.returnValue)){a:{var e=!1;if(0==d.keyCode)try{d.keyCode=-1;break a}catch(f){e=!0}if(e||void 0==d.returnValue)d.returnValue=!0}d=[];for(e=b.b;e;e=e.parentNode)d.push(e);a=a.type;for(e=d.length-1;!b.c&&0<=e;e--){b.b=d[e];var g=cc(d[e],a,!0,b);c=c&&g}for(e=0;!b.c&&e<d.length;e++)b.b=d[e],g=cc(d[e],a,!1,b),c=
c&&g}return c}return dc(a,new T(b,this))}function X(a){a=a[Sb];return a instanceof Qb?a:null}var ec="__closure_events_fn_"+(1E9*Math.random()>>>0);function Xb(a){if("function"==Ea(a))return a;a[ec]||(a[ec]=function(b){return a.handleEvent(b)});return a[ec]};function Y(a){R.call(this);this.c=a;this.a={}}Ia(Y,R);var fc=[];function gc(a,b,c,d){W(a,b,c,d,void 0)}h=Y.prototype;h.ya=function(a,b,c,d,e){return W(this,a,b,c,d,e)};function W(a,b,c,d,e,g){Array.isArray(c)||(c&&(fc[0]=c.toString()),c=fc);for(var f=0;f<c.length;f++){var k=Vb(b,c[f],d||a.handleEvent,e||!1,g||a.c||a);if(!k)break;a.a[k.key]=k}return a}h.ka=function(a,b,c,d){return hc(this,a,b,c,d)};h.xa=function(a,b,c,d,e){return hc(this,a,b,c,d,e)};
function hc(a,b,c,d,e,g){if(Array.isArray(c))for(var f=0;f<c.length;f++)hc(a,b,c[f],d,e,g);else{b=Wb(b,c,d||a.handleEvent,e,g||a.c||a);if(!b)return a;a.a[b.key]=b}return a}h.za=function(a,b,c,d){W(b,a,c,d,this.c||this);return this};h.Aa=function(a,b,c,d,e){W(b,a,c,d,e||this.c||this);return this};h.ja=function(){var a=0,b;for(b in this.a)Object.prototype.hasOwnProperty.call(this.a,b)&&a++;return a};
function ic(a,b,c,d,e,g){if(Array.isArray(c))for(var f=0;f<c.length;f++)ic(a,b,c[f],d,e,g);else d=d||a.handleEvent,e=x(e)?!!e.capture:!!e,g=g||a.c||a,d=Xb(d),e=!!e,b&&b[U]?c=b.B(c,d,e,g):b?(b=X(b))?(c=b.a[c.toString()],b=-1,c&&(b=Rb(c,d,e,g)),c=-1<b?c[b]:null):c=null:c=null,c&&(bc(c),delete a.a[c.key])}h.Ka=function(a,b,c,d,e){ic(b,a,c,d,e||this.c||this,this);return this};function jc(a){Qa(a.a,function(b,c){this.a.hasOwnProperty(c)&&bc(b)},a);a.a={}}h.G=function(){Y.C.G.call(this);jc(this)};
h.handleEvent=function(){throw Error("EventHandler.handleEvent not implemented");};var kc=!1;function lc(a){if((a=a.target)&&1===a.nodeType){var b=lb(a,function(d){return d.hasAttribute&&d.hasAttribute("data-modal-dialog-id")},!0,5);if(b){var c=b.getAttribute("data-modal-dialog-id").trim();c&&(c=document.getElementById(c))&&c instanceof Z&&(c.h=b,c.open=!0)}if(a.classList.contains("devsite-dialog-close")||kb(a))if(a=lb(a,function(d){a:{if(d)for(d=d.constructor;d&&d!==HTMLElement&&d!==Node;){if(d===Z){d=!0;break a}d=Object.getPrototypeOf(d)}d=!1}return d}))a.open=!1}}
function Z(){var a=Q.call(this)||this;a.j=!1;a.g=null;a.f=null;a.a=[];a.h=null;a.c=new Y;a.i=!1;return a}ka(Z,Q);
Z.prototype.attributeChangedCallback=function(a,b,c){if("open"===a)if(null!==c)this.setAttribute("aria-modal","true"),this.setAttribute("aria-role","dialog"),this.dispatchEvent(new CustomEvent("devsite-sitemask-show",{bubbles:!0})),this.dispatchEvent(new CustomEvent("devsite-dialog-show",{bubbles:!0})),this.g=this.parentElement,this.f=this.nextElementSibling,this.b||(this.b=document.createElement("div"),this.b.classList.add("devsite-dialog-wrapper")),this.b.appendChild(this),document.body.appendChild(this.b),
(a=this.querySelector("h3"))&&this.scrollHeight>this.clientHeight?(a.hasAttribute("tabindex")||a.setAttribute("tabindex",-1),a.focus()):this.a.length&&this.a[0].focus();else{a=n(this.querySelectorAll("devsite-youtube"));for(b=a.next();!b.done;b=a.next())b=b.value,b.hasAttribute("action")&&"play"===b.getAttribute("action")&&b.setAttribute("action","pause");this.removeAttribute("aria-modal");this.removeAttribute("aria-role");this.f&&this.f.parentElement===this.g?this.g.insertBefore(this,this.f):this.g.appendChild(this);
(a=this.b)&&a.parentNode&&a.parentNode.removeChild(a);(a=this.querySelector("h3"))&&"-1"===a.getAttribute("tabindex")&&a.removeAttribute("tabindex");this.h&&this.h.focus();this.dispatchEvent(new CustomEvent("devsite-sitemask-hide",{bubbles:!0}));this.dispatchEvent(new CustomEvent("devsite-dialog-hide",{bubbles:!0}))}};
Z.prototype.connectedCallback=function(){var a=this;gc(this.c,document.body,"devsite-before-page-change",function(){a.open=!1});gc(this.c,document.body,"devsite-sitemask-hidden",function(){a.open=!1});kc||(kc=!0,document.addEventListener("click",lc));if(!this.j){this.j=!0;var b=Array.from(this.children).find(function(d){return d.classList.contains("devsite-dialog")});b&&(mc(this,b),this.removeChild(b));b=n(this.querySelectorAll(".devsite-dialog-buttons > a"));for(var c=b.next();!c.done;c=b.next())c=
c.value,c.hasAttribute("tabindex")||c.setAttribute("tabindex",0)}(b=this.querySelector("h3"))&&this.setAttribute("aria-label",b.innerText);nc(this);gc(this.c,this,"keydown",function(d){if(("Tab"===d.key||9===d.L)&&null!=document.activeElement&&a.a.includes(document.activeElement)){var e=a.a.indexOf(document.activeElement);d.shiftKey?a.a[0===e?a.a.length-1:e-1].focus():a.a[e===a.a.length-1?0:e+1].focus();d.A()}});this.i||oc(this)};
function oc(a){var b,c;Ba(new Aa(new xa(function(d){if(1==d.a){b=new H((new URL(document.location.toString())).href);c=b.a.get("dialogOnLoad");if(a.id!=="devsite-dialog-onload-"+c)return d.u(0);a.i=!0;var e=DevsiteApp.whenReady();d.a=3;return{value:e}}a.open=!0;d.a=0})))}function mc(a,b){var c=b.getAttribute("id");c&&a.setAttribute("id",c);a.className=b.className;for(a.classList.remove("devsite-dialog");b.childNodes[0];)a.appendChild(b.childNodes[0])}
function nc(a){a.a=gb(a,function(b){var c;if(c=b instanceof HTMLElement){c="A"==b.tagName&&b.hasAttribute("href")||"INPUT"==b.tagName||"TEXTAREA"==b.tagName||"SELECT"==b.tagName||"BUTTON"==b.tagName?!b.disabled&&(!ib(b)||jb(b)):ib(b)&&jb(b);var d;c&&B?("function"!=Ea(b.getBoundingClientRect)||B&&null==b.parentElement?d={height:b.offsetHeight,width:b.offsetWidth}:d=b.getBoundingClientRect(),d=null!=d&&0<d.height&&0<d.width):d=c;c=d||b.hasAttribute("tabindex")}return c}).sort(function(b,c){b=b.hasAttribute("tabindex")?
parseInt(b.getAttribute("tabindex"),10):0;c=c.hasAttribute("tabindex")?parseInt(c.getAttribute("tabindex"),10):0;return 0<b&&0<c?c-b:0<b?-1:0<c?1:0})}Z.prototype.disconnectedCallback=function(){jc(this.c)};Z.prototype.I=function(){};q.Object.defineProperties(Z.prototype,{open:{configurable:!0,enumerable:!0,get:function(){return this.hasAttribute("open")},set:function(a){a?this.setAttribute("open",this.getAttribute("open")||""):this.removeAttribute("open")}}});
q.Object.defineProperties(Z,{observedAttributes:{configurable:!0,enumerable:!0,get:function(){return["open"]}}});Z.prototype.disconnectedCallback=Z.prototype.disconnectedCallback;Z.prototype.connectedCallback=Z.prototype.connectedCallback;Z.prototype.attributeChangedCallback=Z.prototype.attributeChangedCallback;try{window.customElements.define("devsite-dialog",Z)}catch(a){console.warn("devsite.app.customElement.DevsiteDialog",a)};}).call(this);
